// Generated by make_conceptmap_fsh.py - do not edit by hand.
// Source: input/glossary_mappings.csv (confirmed rows only).
// Regenerate rather than patching: the display page beside this
// file is generated from the same rows and must agree with it.

Instance: DrpModelToGlossary
InstanceOf: ConceptMap
Usage: #definition
* url = "http://example.org/ConceptMap/DrpModelToGlossary"
* name = "DrpModelToGlossary"
* title = "drp logical model elements to Common Glossary concepts"
* status = #active
* experimental = false
* date = "2026-09-07"
* copyright = "Published for information. This mapping carries no conformance requirement and does not modify the logical models, which are published as released. It remains subject to review: coverage will be extended and individual mappings may be revised in subsequent versions."
* description = "Maps elements of the drp logical models to the concepts of the Belgian Common Glossary. Published as a ConceptMap so the StructureDefinitions remain exactly as released and a change of mapping is not a change of model."

* group[+]
  * source = "https://www.ehealth.fgov.be/standards/fhir/drp/StructureDefinition/BeModelAnnex81"
  * target = "http://example.org/CodeSystem/BeSafeShareGlossary"
  * element[+]
    * code = #BeModelAnnex81.author
    * display = "The person who encodes the prescription (e.g. a doctor, nurse, midwife or dentist) and takes responsibility for their content. The unique identifier must be the National Register Number (NISS) or bis number."
    * target[+]
      * code = #Recorder
      * display = "Recorder"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelAnnex81.identifier
    * display = "Business identifier of the Annex81 proposal / approval"
    * target[+]
      * code = #BusinessIdentifier
      * display = "BusinessIdentifier"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelAnnex81.originRequestId
    * display = "Reference to the original prescription on which the prescription is based (prescriptionId), care plan, follow-up path, …. referenceId. Reference to the CarePlan that addresses this prescription."
    * target[+]
      * code = #OriginatingRequest
      * display = "OriginatingRequest"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelAnnex81.patient
    * display = "The patient's identification. The unique identifier must be the National Patient Registry Number (NISS) or the patient bis"
    * target[+]
      * code = #Patient
      * display = "Patient"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelAnnex81.recordedDate
    * display = "Date of encoding of the information by the Recorder."
    * target[+]
      * code = #RecordedDate
      * display = "RecordedDate"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelAnnex81.status
    * display = "Is the status of the referral prescription (e.g. planned, complete, stopped, suspended, in progress, ….)"
    * target[+]
      * code = #Status
      * display = "Status"
      * equivalence = #equivalent

* group[+]
  * source = "https://www.ehealth.fgov.be/standards/fhir/drp/StructureDefinition/BeModelAssignment"
  * target = "http://example.org/CodeSystem/BeSafeShareGlossary"
  * element[+]
    * code = #BeModelAssignment.identifier
    * display = "Business identifier. Absent during creation by client software, otherwise always present."
    * target[+]
      * code = #BusinessIdentifier
      * display = "BusinessIdentifier"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelAssignment.originRequestId
    * display = "Reference to the associated referral prescription"
    * target[+]
      * code = #OriginatingRequest
      * display = "OriginatingRequest"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelAssignment.performer
    * display = "Information about the intended performer of the task"
    * target[+]
      * code = #Performer
      * display = "Performer"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelAssignment.status
    * display = "Status of the task"
    * target[+]
      * code = #Status
      * display = "Status"
      * equivalence = #equivalent

* group[+]
  * source = "https://www.ehealth.fgov.be/standards/fhir/drp/StructureDefinition/BeModelOrganisationClaim"
  * target = "http://example.org/CodeSystem/BeSafeShareGlossary"
  * element[+]
    * code = #BeModelOrganisationClaim.identifier
    * display = "Business identifier"
    * target[+]
      * code = #BusinessIdentifier
      * display = "BusinessIdentifier"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelOrganisationClaim.status
    * display = "Status of the task"
    * target[+]
      * code = #Status
      * display = "Status"
      * equivalence = #equivalent

* group[+]
  * source = "https://www.ehealth.fgov.be/standards/fhir/drp/StructureDefinition/BeModelReferralPrescription"
  * target = "http://example.org/CodeSystem/BeSafeShareGlossary"
  * element[+]
    * code = #BeModelReferralPrescription.author
    * display = "The person who encodes the prescription (e.g. a doctor, nurse, midwife or dentist) and takes responsibility for their content. The unique identifier must be: NISS, National Registry Number or Bis Requester"
    * target[+]
      * code = #Recorder
      * display = "Recorder"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelReferralPrescription.bodyLocation
    * display = "Anatomical location where the treatment should be applied (for example: 'Left arm')."
    * target[+]
      * code = #BodyLocation
      * display = "BodyLocation"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelReferralPrescription.creationDate
    * display = "Date of creation of the referral prescription"
    * target[+]
      * code = #RecordedDate
      * display = "RecordedDate"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelReferralPrescription.identifier
    * display = "Business identifier of the request"
    * target[+]
      * code = #BusinessIdentifier
      * display = "BusinessIdentifier"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelReferralPrescription.originRequestId
    * display = "Reference to the ID of the original request (useful when the request is an extension of another one)."
    * target[+]
      * code = #OriginatingRequest
      * display = "OriginatingRequest"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelReferralPrescription.patient
    * display = "Identification of the patient. The unique identifier must be: NISS, National Registry Number or Bis Patient"
    * target[+]
      * code = #Patient
      * display = "Patient"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelReferralPrescription.recordedDate
    * display = "Date of recording of the information by the Recorder."
    * target[+]
      * code = #RecordedDate
      * display = "RecordedDate"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelReferralPrescription.status
    * display = "Is the status of the referral prescription (e.g. planned, complete, stopped, suspended, in progress, ….)"
    * target[+]
      * code = #Status
      * display = "Status"
      * equivalence = #equivalent

* group[+]
  * source = "https://www.ehealth.fgov.be/standards/fhir/drp/StructureDefinition/BeModelTreatmentStatus"
  * target = "http://example.org/CodeSystem/BeSafeShareGlossary"
  * element[+]
    * code = #BeModelTreatmentStatus.identifier
    * display = "UUID (see Doc: https://docs.google.com/document/d/13qamEPfdQ2HgUiXmjwHQNchpEU3LsQHF5MN9jKufX2g/edit?usp=sharing ) Absent during creation by client software, otherwise always present."
    * target[+]
      * code = #BusinessIdentifier
      * display = "BusinessIdentifier"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelTreatmentStatus.status
    * display = "Status of the task"
    * target[+]
      * code = #Status
      * display = "Status"
      * equivalence = #equivalent
