// Generated by make_conceptmap_fsh.py - do not edit by hand.
// Source: input/glossary_mappings.csv (confirmed rows only).
// Regenerate rather than patching: the display page beside this
// file is generated from the same rows and must agree with it.

Instance: ChildreportModelToGlossary
InstanceOf: ConceptMap
Usage: #definition
* extension[+].url = "http://hl7.org/fhir/StructureDefinition/structuredefinition-fmm"
* extension[=].valueInteger = 1
* url = "http://example.org/ConceptMap/ChildreportModelToGlossary"
* name = "ChildreportModelToGlossary"
* version = "0.9.0"
* title = "childreport logical model elements to Common Glossary concepts"
* status = #active
* experimental = false
* date = "2026-09-07"
* copyright = "First public release - agreed by the editors and open for review. The mapping is informative: the logical models are published as released and are unchanged by it. Coverage will be extended and individual mappings may be revised as review progresses."
* description = "Maps elements of the childreport logical models to the concepts of the Belgian Common Glossary. Published as a ConceptMap so the StructureDefinitions remain exactly as released and a change of mapping is not a change of model."

* group[+]
  * source = "https://www.ehealth.fgov.be/standards/fhir/childreport/StructureDefinition/BeModelChildReport"
  * target = "http://example.org/CodeSystem/BeSafeShareGlossary"
  * element[+]
    * code = #BeModelChildReport.bacterialMeningitis.subject
    * display = "Child"
    * target[+]
      * code = #Patient
      * display = "Patient"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelChildReport.eyeResults.eyeMovementAndPosition.subject
    * display = "Child that the report is about"
    * target[+]
      * code = #Patient
      * display = "Patient"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelChildReport.eyeResults.eyeRemarks.subject
    * display = "Child that the report is about"
    * target[+]
      * code = #Patient
      * display = "Patient"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelChildReport.eyeResults.inspectionPupilAbnormal.subject
    * display = "Child that the report is about"
    * target[+]
      * code = #Patient
      * display = "Patient"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelChildReport.eyeScreening.subject
    * display = "Child that the report is about"
    * target[+]
      * code = #Patient
      * display = "Patient"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelChildReport.neonatalHearingScreeningLeft.subject
    * display = "Child that the report is about"
    * target[+]
      * code = #Patient
      * display = "Patient"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelChildReport.neonatalHearingScreeningRight.subject
    * display = "Child that the report is about"
    * target[+]
      * code = #Patient
      * display = "Patient"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelChildReport.pregnancyDetails.durationOfPregnancy.subject
    * display = "Child"
    * target[+]
      * code = #Patient
      * display = "Patient"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelChildReport.pregnancyDetails.pregnancyCMVInfection.subject
    * display = "Child"
    * target[+]
      * code = #Patient
      * display = "Patient"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelChildReport.severeHeadTrauma.subject
    * display = "Child that the report is about"
    * target[+]
      * code = #Patient
      * display = "Patient"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelChildReport.subject
    * display = "Child that the report is about"
    * target[+]
      * code = #Patient
      * display = "Patient"
      * equivalence = #equivalent
