@startuml
skinparam shadowing false
skinparam classAttributeIconSize 0
skinparam linetype ortho
skinparam class {
  BackgroundColor #FEFECE
  BorderColor #000000
  ArrowColor #000000
  FontStyle bold
  AttributeFontStyle normal
}
hide circle
hide empty members

class "BeModelDiagnosticReportDiabetes" as BeModelDiagnosticReportDiabetes <<model>> {
}

class "UniqueIdentifierNational" as BeModelDiagnosticReportDiabetes_UniqueIdentifierNational <<Identifier>> {
}

class "BusinessIdentifier" as BeModelDiagnosticReportDiabetes_BusinessIdentifier <<Identifier>> {
}

class "RecordedDate" as BeModelDiagnosticReportDiabetes_RecordedDate <<dateTime>> {
}

class "ObservationPeriod" as BeModelDiagnosticReportDiabetes_ObservationPeriod <<Period>> {
}

class "Patient" as BeModelDiagnosticReportDiabetes_Patient <<Identifier>> {
}

class "Recorder" as BeModelDiagnosticReportDiabetes_Recorder <<Identifier>> {
}

class "Performer" as BeModelDiagnosticReportDiabetes_Performer <<Identifier>> {
}

class "Interpreter" as BeModelDiagnosticReportDiabetes_Interpreter <<Identifier>> {
}

class "Category" as BeModelDiagnosticReportDiabetes_Category <<CodeableConcept>> {
}

class "Qualification" as BeModelDiagnosticReportDiabetes_Qualification <<CodeableConcept>> {
}

class "Device" as BeModelDiagnosticReportDiabetes_Device <<Identifier>> {
}

class "Code" as BeModelDiagnosticReportDiabetes_Code <<CodeableConcept>> {
}

class "DerivedObservations" as BeModelDiagnosticReportDiabetes_DerivedObservations <<Observation>> {
}

class "MeasurementObservations" as BeModelDiagnosticReportDiabetes_MeasurementObservations <<Observation>> {
}

class "Diagnosis" as BeModelDiagnosticReportDiabetes_Diagnosis <<Condition>> {
}

class "Note" as BeModelDiagnosticReportDiabetes_Note <<Annotation>> {
}

class "Document" as BeModelDiagnosticReportDiabetes_Document <<Binary>> {
}

class "Status" as BeModelDiagnosticReportDiabetes_Status <<code>> {
}

BeModelDiagnosticReportDiabetes *-- "1..1" BeModelDiagnosticReportDiabetes_UniqueIdentifierNational
BeModelDiagnosticReportDiabetes *-- "0..1" BeModelDiagnosticReportDiabetes_BusinessIdentifier
BeModelDiagnosticReportDiabetes *-- "1..1" BeModelDiagnosticReportDiabetes_RecordedDate
BeModelDiagnosticReportDiabetes *-- "1..1" BeModelDiagnosticReportDiabetes_ObservationPeriod
BeModelDiagnosticReportDiabetes *-- "1..1" BeModelDiagnosticReportDiabetes_Patient
BeModelDiagnosticReportDiabetes *-- "1..1" BeModelDiagnosticReportDiabetes_Recorder
BeModelDiagnosticReportDiabetes *-- "1..1" BeModelDiagnosticReportDiabetes_Performer
BeModelDiagnosticReportDiabetes *-- "0..1" BeModelDiagnosticReportDiabetes_Interpreter
BeModelDiagnosticReportDiabetes *-- "1..*" BeModelDiagnosticReportDiabetes_Category
BeModelDiagnosticReportDiabetes *-- "1..1" BeModelDiagnosticReportDiabetes_Qualification
BeModelDiagnosticReportDiabetes *-- "0..1" BeModelDiagnosticReportDiabetes_Device
BeModelDiagnosticReportDiabetes *-- "1..1" BeModelDiagnosticReportDiabetes_Code
BeModelDiagnosticReportDiabetes *-- "0..*" BeModelDiagnosticReportDiabetes_DerivedObservations
BeModelDiagnosticReportDiabetes *-- "0..*" BeModelDiagnosticReportDiabetes_MeasurementObservations
BeModelDiagnosticReportDiabetes *-- "0..*" BeModelDiagnosticReportDiabetes_Diagnosis
BeModelDiagnosticReportDiabetes *-- "0..*" BeModelDiagnosticReportDiabetes_Note
BeModelDiagnosticReportDiabetes *-- "0..1" BeModelDiagnosticReportDiabetes_Document
BeModelDiagnosticReportDiabetes *-- "0..1" BeModelDiagnosticReportDiabetes_Status
@enduml