@startuml
skinparam ClassBackgroundColor #B5E8F7
skinparam linetype polyline
hide circle
hide stereotype

class "**BeModelAssignment**" as BeModelAssignment {
|_ identifier 1..1   <<Identifier>>  
|_ intent 1..1   <<CodeableConcept>>  
|_ status 1..1   <<CodeableConcept>>  
|_ statusReason 0..1   <<CodeableConcept>>  
|_ originRequestId 1..1   <<Identifier>>  
|_ treatmentStatusId 1..1   <<Reference(BeModelTreatmentStatus)>>  
|_ organizationID 0..1   <<Reference(BeModelOrganisationClaim)>>  
|_ performer 1..*  
  |_ role 1..1   <<CodeableConcept>>  
  |_ actor 0..1   <<Identifier>>  
  |_ organisation 0..1   <<Identifier>>  
  |_ startdate 0..1   <<dateTime>>  
  |_ endDate 0..1   <<dateTime>>  
--
}

@enduml