@startuml
skinparam ClassBackgroundColor #B5E8F7
skinparam linetype polyline
hide circle
hide stereotype

class "**BeModelCarePlan**" as BeModelCarePlan {
|_ identifier 0..*   <<Identifier>>  
|_ name 0..1   <<string>>  
|_ category 0..*   <<CodeableConcept>>  
|_ basedOn 0..*   <<Reference>>  
|_ partOf 0..*   <<Reference>>  
|_ status 0..1   <<code>>  
|_ description 0..1   <<string>>  
|_ instantiates 0..*   <<Reference>>  
|_ subject 0..1   <<Reference>>  
|_ period 0..1   <<Period>>  
|_ author 0..*   <<Reference>>  
|_ careTeam 0..*   <<Reference>>  
|_ goal 0..*   <<Reference>>  
|_ participant 0..*  
  |_ role 0..1   <<CodeableConcept>>  
  |_ member 1..1   <<Reference>>  
  |_ period 0..1   <<Period>>  
|_ managingOrganization 0..1   <<Reference>>  
|_ contact 0..*   <<ContactPoint>>  
|_ note 0..*   <<string>>  
--
}

@enduml