@startuml
left to right direction
skinparam shadowing false
skinparam nodesep 10
skinparam ranksep 40
skinparam classAttributeIconSize 0
skinparam class {
  FontStyle italic
  BackgroundColor<<rootconcept>> #FAC08F
  BorderColor<<rootconcept>> #E36C0A
  BackgroundColor<<data>> #B8CCE4
  BorderColor<<data>> #4F81BD
  BackgroundColor<<reference>> #D9D9D9
  BorderColor<<reference>> #808080
  BackgroundColor<<value set>> #C3D69B
  BorderColor<<value set>> #77933C
  ArrowColor #4F81BD
}
hide circle
hide empty members

class "BeModelObservationDiabetes" as BeModelObservationDiabetes <<rootconcept>> {
}

class "UniqueIdentifier" as BeModelObservationDiabetes_UniqueIdentifier <<data>> {
}

class "RecordedDate" as BeModelObservationDiabetes_RecordedDate <<data>> {
}

class "ObservationPeriod" as BeModelObservationDiabetes_ObservationPeriod <<data>> {
}

class "Patient" as BeModelObservationDiabetes_Patient <<data>> {
}

class "Recorder" as BeModelObservationDiabetes_Recorder <<data>> {
}

class "Category" as BeModelObservationDiabetes_Category <<data>> {
}

class "Status" as BeModelObservationDiabetes_Status <<data>> {
}

class "Code" as BeModelObservationDiabetes_Code <<data>> {
}

class "Value" as BeModelObservationDiabetes_Value <<data>> {
}

class "ReferenceRange" as BeModelObservationDiabetes_ReferenceRange <<data>> {
}

BeModelObservationDiabetes_UniqueIdentifier "1..1" --> BeModelObservationDiabetes
BeModelObservationDiabetes_RecordedDate "1..1" --> BeModelObservationDiabetes
BeModelObservationDiabetes_ObservationPeriod "1..1" --> BeModelObservationDiabetes
BeModelObservationDiabetes_Patient "1..1" --> BeModelObservationDiabetes
BeModelObservationDiabetes_Recorder "1..1" --> BeModelObservationDiabetes
BeModelObservationDiabetes_Category "1..*" --> BeModelObservationDiabetes
BeModelObservationDiabetes_Status "0..1" --> BeModelObservationDiabetes
BeModelObservationDiabetes_Code "1..1" --> BeModelObservationDiabetes
BeModelObservationDiabetes_Value "1..1" --> BeModelObservationDiabetes
BeModelObservationDiabetes_ReferenceRange "0..*" --> BeModelObservationDiabetes
@enduml