@startuml
left to right direction
skinparam shadowing false
skinparam nodesep 10
skinparam ranksep 40
skinparam classAttributeIconSize 0
skinparam class {
  FontStyle italic
  BackgroundColor<<rootconcept>> #FAC08F
  BorderColor<<rootconcept>> #E36C0A
  BackgroundColor<<data>> #B8CCE4
  BorderColor<<data>> #4F81BD
  BackgroundColor<<reference>> #D9D9D9
  BorderColor<<reference>> #808080
  BackgroundColor<<value set>> #C3D69B
  BorderColor<<value set>> #77933C
  ArrowColor #4F81BD
}
hide circle
hide empty members

class "BeModelPatient" as BeModelPatient <<rootconcept>> {
}

class "names" as BeModelPatient_names <<rootconcept>> {
}

class "usage" as BeModelPatient_names_usage <<data>> {
}

class "familyname" as BeModelPatient_names_familyname <<data>> {
}

class "firstnames" as BeModelPatient_names_firstnames <<data>> {
}

class "title" as BeModelPatient_names_title <<data>> {
}

class "period" as BeModelPatient_names_period <<data>> {
}

class "birth" as BeModelPatient_birth <<rootconcept>> {
}

class "address" as BeModelPatient_birth_address <<data>> {
}

class "date" as BeModelPatient_birth_date <<data>> {
}

class "gender" as BeModelPatient_gender <<rootconcept>> {
}

class "administrative" as BeModelPatient_gender_administrative <<data>> {
}

class "atbirth" as BeModelPatient_gender_atbirth <<data>> {
}

class "social" as BeModelPatient_gender_social <<data>> {
}

class "nationality" as BeModelPatient_nationality <<data>> {
}

class "residence" as BeModelPatient_residence <<data>> {
}

class "death" as BeModelPatient_death <<rootconcept>> {
}

class "date" as BeModelPatient_death_date <<data>> {
}

class "deceased" as BeModelPatient_death_deceased <<data>> {
}

class "maritalstatus" as BeModelPatient_maritalstatus <<data>> {
}

BeModelPatient_names "0..*" --> BeModelPatient
BeModelPatient_names_usage "0..1" --> BeModelPatient_names
BeModelPatient_names_familyname "0..1" --> BeModelPatient_names
BeModelPatient_names_firstnames "0..1" --> BeModelPatient_names
BeModelPatient_names_title "0..1" --> BeModelPatient_names
BeModelPatient_names_period "0..1" --> BeModelPatient_names
BeModelPatient_birth "0..1" --> BeModelPatient
BeModelPatient_birth_address "0..1" --> BeModelPatient_birth
BeModelPatient_birth_date "0..1" --> BeModelPatient_birth
BeModelPatient_gender "0..1" --> BeModelPatient
BeModelPatient_gender_administrative "0..1" --> BeModelPatient_gender
BeModelPatient_gender_atbirth "0..1" --> BeModelPatient_gender
BeModelPatient_gender_social "0..1" --> BeModelPatient_gender
BeModelPatient_nationality "0..*" --> BeModelPatient
BeModelPatient_residence "0..*" --> BeModelPatient
BeModelPatient_death "0..1" --> BeModelPatient
BeModelPatient_death_date "0..1" --> BeModelPatient_death
BeModelPatient_death_deceased "0..1" --> BeModelPatient_death
BeModelPatient_maritalstatus "0..1" --> BeModelPatient
@enduml