@startuml
skinparam ClassBackgroundColor #B5E8F7
skinparam linetype polyline
hide circle
hide stereotype

class "**BeModelGoal**" as BeModelGoal {
|_ identifier 0..*   <<Identifier>>  
|_ name 1..1   <<string>>  
|_ category 1..*   <<CodeableConcept>>  
|_ status 1..1   <<code>>  
--
}

@enduml