@startuml
skinparam ClassBackgroundColor #B5E8F7
skinparam linetype polyline
hide circle
hide stereotype

class "**BeModelEAgreement**" as BeModelEAgreement {
|_ serviceProvider 0..1   <<Identifier>>  
|_ patient 1..1   <<Identifier>>  
|_ eAgreementType 1..1   <<CodeableConcept>>  
|_ decisionId 0..1   <<Identifier>>  
|_ desiredStartDate 0..1   <<dateTime>>  
|_ pathologyOnsetDate 0..1   <<dateTime>>  
|_ assessmentCompletionDates 0..5   <<dateTime>>  
|_ pathologicalSituation 0..1   <<CodeableConcept>>  
|_ notes 0..1   <<Annotation>>  
|_ prescription 0..1  
  |_ identification 0..1   <<Identifier>>  
  |_ prescriber 1..1   <<Identifier>>  
  |_ authoredOn 1..1   <<dateTime>>  
  |_ quantity 1..1   <<positiveInt>>  
  |_ scan 0..1   <<Binary>>  
|_ related 0..1  
  |_ identification 0..1   <<Identifier>>  
  |_ prescriber 1..1   <<Identifier>>  
  |_ authoredOn 1..1   <<dateTime>>  
  |_ quantity 1..1   <<positiveInt>>  
  |_ scan 0..1   <<Binary>>  
|_ attachment 0..*  
  |_ kind 1..1   <<CodeableConcept>>  
  |_ title 0..1   <<string>>  
  |_ scan 1..1   <<Binary>>  
--
}

@enduml