@startuml
left to right direction
skinparam shadowing false
skinparam nodesep 10
skinparam ranksep 40
skinparam classAttributeIconSize 0
skinparam class {
  FontStyle italic
  BackgroundColor<<rootconcept>> #FAC08F
  BorderColor<<rootconcept>> #E36C0A
  BackgroundColor<<data>> #B8CCE4
  BorderColor<<data>> #4F81BD
  BackgroundColor<<reference>> #D9D9D9
  BorderColor<<reference>> #808080
  BackgroundColor<<value set>> #C3D69B
  BorderColor<<value set>> #77933C
  ArrowColor #4F81BD
}
hide circle
hide empty members

class "BeModelTask" as BeModelTask <<rootconcept>> {
}

class "identifier" as BeModelTask_identifier <<data>> {
}

class "author" as BeModelTask_author <<reference>> {
}

class "status" as BeModelTask_status <<data>> {
}

class "priority" as BeModelTask_priority <<data>> {
}

class "owner" as BeModelTask_owner <<data>> {
}

BeModelTask_identifier "0..*" --> BeModelTask
BeModelTask_author "1..1" --> BeModelTask
BeModelTask_status "1..1" --> BeModelTask
BeModelTask_priority "0..1" --> BeModelTask
BeModelTask_owner "0..*" --> BeModelTask
@enduml