@startuml
skinparam shadowing false
skinparam classAttributeIconSize 0
skinparam linetype ortho
skinparam class {
  BackgroundColor #FEFECE
  BorderColor #000000
  ArrowColor #000000
  FontStyle bold
  AttributeFontStyle normal
}
hide circle
hide empty members

class "BeModelPopulationScreeningPlan" as BeModelPopulationScreeningPlan <<model>> {
}

class "patient" as BeModelPopulationScreeningPlan_patient <<Reference(Patient)>> {
}

class "screeningType" as BeModelPopulationScreeningPlan_screeningType <<CodeableConcept>> {
}

class "screeningEpisode" as BeModelPopulationScreeningPlan_screeningEpisode <<BeModelPopulationScreening>> {
}

BeModelPopulationScreeningPlan *-- "1..1" BeModelPopulationScreeningPlan_patient
BeModelPopulationScreeningPlan *-- "1..1" BeModelPopulationScreeningPlan_screeningType
BeModelPopulationScreeningPlan *-- "0..*" BeModelPopulationScreeningPlan_screeningEpisode
@enduml