@startuml
left to right direction
skinparam shadowing false
skinparam nodesep 10
skinparam ranksep 40
skinparam classAttributeIconSize 0
skinparam class {
  FontStyle italic
  BackgroundColor<<rootconcept>> #FAC08F
  BorderColor<<rootconcept>> #E36C0A
  BackgroundColor<<data>> #B8CCE4
  BorderColor<<data>> #4F81BD
  BackgroundColor<<reference>> #D9D9D9
  BorderColor<<reference>> #808080
  BackgroundColor<<value set>> #C3D69B
  BorderColor<<value set>> #77933C
  ArrowColor #4F81BD
}
hide circle
hide empty members

class "BeModelCarePlan" as BeModelCarePlan <<rootconcept>> {
}

class "identifier" as BeModelCarePlan_identifier <<data>> {
}

class "name" as BeModelCarePlan_name <<data>> {
}

class "category" as BeModelCarePlan_category <<data>> {
}

class "basedOn" as BeModelCarePlan_basedOn <<reference>> {
}

class "partOf" as BeModelCarePlan_partOf <<reference>> {
}

class "status" as BeModelCarePlan_status <<data>> {
}

class "description" as BeModelCarePlan_description <<data>> {
}

class "instantiates" as BeModelCarePlan_instantiates <<reference>> {
}

class "subject" as BeModelCarePlan_subject <<reference>> {
}

class "period" as BeModelCarePlan_period <<data>> {
}

class "author" as BeModelCarePlan_author <<reference>> {
}

class "careTeam" as BeModelCarePlan_careTeam <<reference>> {
}

class "goal" as BeModelCarePlan_goal <<reference>> {
}

class "participant" as BeModelCarePlan_participant <<rootconcept>> {
}

class "role" as BeModelCarePlan_participant_role <<data>> {
}

class "member" as BeModelCarePlan_participant_member <<reference>> {
}

class "period" as BeModelCarePlan_participant_period <<data>> {
}

class "managingOrganization" as BeModelCarePlan_managingOrganization <<reference>> {
}

class "contact" as BeModelCarePlan_contact <<data>> {
}

class "note" as BeModelCarePlan_note <<data>> {
}

BeModelCarePlan_identifier "0..*" --> BeModelCarePlan
BeModelCarePlan_name "0..1" --> BeModelCarePlan
BeModelCarePlan_category "0..*" --> BeModelCarePlan
BeModelCarePlan_basedOn "0..*" --> BeModelCarePlan
BeModelCarePlan_partOf "0..*" --> BeModelCarePlan
BeModelCarePlan_status "0..1" --> BeModelCarePlan
BeModelCarePlan_description "0..1" --> BeModelCarePlan
BeModelCarePlan_instantiates "0..*" --> BeModelCarePlan
BeModelCarePlan_subject "0..1" --> BeModelCarePlan
BeModelCarePlan_period "0..1" --> BeModelCarePlan
BeModelCarePlan_author "0..*" --> BeModelCarePlan
BeModelCarePlan_careTeam "0..*" --> BeModelCarePlan
BeModelCarePlan_goal "0..*" --> BeModelCarePlan
BeModelCarePlan_participant "0..*" --> BeModelCarePlan
BeModelCarePlan_participant_role "0..1" --> BeModelCarePlan_participant
BeModelCarePlan_participant_member "1..1" --> BeModelCarePlan_participant
BeModelCarePlan_participant_period "0..1" --> BeModelCarePlan_participant
BeModelCarePlan_managingOrganization "0..1" --> BeModelCarePlan
BeModelCarePlan_contact "0..*" --> BeModelCarePlan
BeModelCarePlan_note "0..*" --> BeModelCarePlan
@enduml