@startuml
skinparam ClassBackgroundColor #B5E8F7
skinparam linetype polyline
hide circle
hide stereotype

class "**BeModelClinicalObservation**" as BeModelClinicalObservation {
|_ identifier 1..*   <<Identifier>>  
|_ recordedDate 1..1   <<dateTime>>  
|_ observationDate[x] 1..1   <<dateTime | Period>>  
|_ recorder 1..1   <<Reference>>  
|_ performer 0..1   <<Reference>>  
|_ patient 1..1   <<Reference>>  
|_ request 0..1   <<Reference>>  
|_ partOfProcedure 0..*   <<Reference>>  
|_ specimen 0..1   <<Reference>>  
|_ device 0..1   <<Reference>>  
|_ category 0..*   <<CodeableConcept>>  
|_ code 1..1   <<CodeableConcept>>  
|_ value[x] 0..1   <<Quantity | CodeableConcept | string | boolean | integer | Range | Ratio | time | dateTime | Period>>  
|_ member 0..*   <<Reference(BeModelClinicalObservation)>>  
|_ status 1..1   <<code>>  
|_ interpretation 0..*   <<CodeableConcept>>  
|_ referenceRange 0..*  
  |_ low 0..1   <<Quantity>>  
  |_ high 0..1   <<Quantity>>  
|_ bodySite 0..1   <<BeModelBodySite>>  
|_ certainty 0..1   <<CodeableConcept>>  
|_ note 0..*   <<Annotation>>  
--
}

@enduml