@startuml
skinparam ClassBackgroundColor #B5E8F7
skinparam linetype polyline
hide circle
hide stereotype

class "**BeModelDocument**" as BeModelDocument {
|_ identifier 0..*   <<Identifier>>  
|_ type 1..1   <<CodeableConcept>>  
|_ dateTime 1..1   <<dateTime>>  
|_ title 0..1   <<string>>  
|_ status 0..1   <<code>>  
|_ language 0..1   <<code>>  
|_ subject 0..1   <<Reference>>  
|_ author 0..*   <<Reference>>  
|_ section 0..*  
  |_ code 0..1   <<CodeableConcept>>  
  |_ entry 0..*   <<Reference>>  
  |_ section 0..*   <<see BeModelDocument.section>>  
|_ entries 0..*  
  |_ reference 1..1   <<Reference>>  
|_ presentedForm 0..*   <<Attachment>>  
--
}

@enduml