@startuml
skinparam ClassBackgroundColor #B5E8F7
skinparam linetype polyline
hide circle
hide stereotype

class "**BeModelVaccinationReduced**" as BeModelVaccinationReduced {
|_ patient 1..1   <<Reference(Patient)>>  
|_ performer 1..1   <<Reference(Practitioner)>>  
|_ administeredProduct 1..1  
  |_ product 1..1   <<Coding>>  
  |_ description 1..1   <<string>>  
  |_ lotNumber 0..1   <<string>>  
|_ identifier 0..1   <<Identifier>>  
|_ vaccinationDate[x] 0..1   <<dateTime | string>>  
|_ recorded 1..1   <<dateTime>>  
|_ doseQuantity 0..1   <<BackboneElement>>  
|_ targetDisease 1..1   <<CodeableConcept>>  
|_ sideEffects 0..1   <<Attachment>>  
|_ cause 0..1   <<CodeableConcept>>  
--
}

@enduml