@startuml
skinparam shadowing false
skinparam classAttributeIconSize 0
skinparam linetype ortho
skinparam class {
  BackgroundColor #FEFECE
  BorderColor #000000
  ArrowColor #000000
  FontStyle bold
  AttributeFontStyle normal
}
hide circle
hide empty members

class "BeModelBodySite" as BeModelBodySite <<model>> {
}

class "bodyLocation" as BeModelBodySite_bodyLocation <<CodeableConcept>> {
}

class "bodyLaterality" as BeModelBodySite_bodyLaterality <<CodeableConcept>> {
}

class "bodyTopography" as BeModelBodySite_bodyTopography <<CodeableConcept>> {
}

BeModelBodySite *-- "0..1" BeModelBodySite_bodyLocation
BeModelBodySite *-- "0..1" BeModelBodySite_bodyLaterality
BeModelBodySite *-- "0..1" BeModelBodySite_bodyTopography
@enduml