@startuml
left to right direction
skinparam shadowing false
skinparam nodesep 10
skinparam ranksep 40
skinparam classAttributeIconSize 0
skinparam class {
  FontStyle italic
  BackgroundColor<<rootconcept>> #FAC08F
  BorderColor<<rootconcept>> #E36C0A
  BackgroundColor<<data>> #B8CCE4
  BorderColor<<data>> #4F81BD
  BackgroundColor<<reference>> #D9D9D9
  BorderColor<<reference>> #808080
  BackgroundColor<<value set>> #C3D69B
  BorderColor<<value set>> #77933C
  ArrowColor #4F81BD
}
hide circle
hide empty members

class "BeModelEAgreement" as BeModelEAgreement <<rootconcept>> {
}

class "serviceProvider" as BeModelEAgreement_serviceProvider <<data>> {
}

class "patient" as BeModelEAgreement_patient <<data>> {
}

class "eAgreementType" as BeModelEAgreement_eAgreementType <<data>> {
}

class "decisionId" as BeModelEAgreement_decisionId <<data>> {
}

class "desiredStartDate" as BeModelEAgreement_desiredStartDate <<data>> {
}

class "pathologyOnsetDate" as BeModelEAgreement_pathologyOnsetDate <<data>> {
}

class "assessmentCompletionDates" as BeModelEAgreement_assessmentCompletionDates <<data>> {
}

class "pathologicalSituation" as BeModelEAgreement_pathologicalSituation <<data>> {
}

class "notes" as BeModelEAgreement_notes <<data>> {
}

class "prescription" as BeModelEAgreement_prescription <<rootconcept>> {
}

class "identification" as BeModelEAgreement_prescription_identification <<data>> {
}

class "prescriber" as BeModelEAgreement_prescription_prescriber <<data>> {
}

class "authoredOn" as BeModelEAgreement_prescription_authoredOn <<data>> {
}

class "quantity" as BeModelEAgreement_prescription_quantity <<data>> {
}

class "scan" as BeModelEAgreement_prescription_scan <<data>> {
}

class "related" as BeModelEAgreement_related <<rootconcept>> {
}

class "identification" as BeModelEAgreement_related_identification <<data>> {
}

class "prescriber" as BeModelEAgreement_related_prescriber <<data>> {
}

class "authoredOn" as BeModelEAgreement_related_authoredOn <<data>> {
}

class "quantity" as BeModelEAgreement_related_quantity <<data>> {
}

class "scan" as BeModelEAgreement_related_scan <<data>> {
}

class "attachment" as BeModelEAgreement_attachment <<rootconcept>> {
}

class "kind" as BeModelEAgreement_attachment_kind <<data>> {
}

class "title" as BeModelEAgreement_attachment_title <<data>> {
}

class "scan" as BeModelEAgreement_attachment_scan <<data>> {
}

BeModelEAgreement_serviceProvider "0..1" --> BeModelEAgreement
BeModelEAgreement_patient "1..1" --> BeModelEAgreement
BeModelEAgreement_eAgreementType "1..1" --> BeModelEAgreement
BeModelEAgreement_decisionId "0..1" --> BeModelEAgreement
BeModelEAgreement_desiredStartDate "0..1" --> BeModelEAgreement
BeModelEAgreement_pathologyOnsetDate "0..1" --> BeModelEAgreement
BeModelEAgreement_assessmentCompletionDates "0..5" --> BeModelEAgreement
BeModelEAgreement_pathologicalSituation "0..1" --> BeModelEAgreement
BeModelEAgreement_notes "0..1" --> BeModelEAgreement
BeModelEAgreement_prescription "0..1" --> BeModelEAgreement
BeModelEAgreement_prescription_identification "0..1" --> BeModelEAgreement_prescription
BeModelEAgreement_prescription_prescriber "1..1" --> BeModelEAgreement_prescription
BeModelEAgreement_prescription_authoredOn "1..1" --> BeModelEAgreement_prescription
BeModelEAgreement_prescription_quantity "1..1" --> BeModelEAgreement_prescription
BeModelEAgreement_prescription_scan "0..1" --> BeModelEAgreement_prescription
BeModelEAgreement_related "0..1" --> BeModelEAgreement
BeModelEAgreement_related_identification "0..1" --> BeModelEAgreement_related
BeModelEAgreement_related_prescriber "1..1" --> BeModelEAgreement_related
BeModelEAgreement_related_authoredOn "1..1" --> BeModelEAgreement_related
BeModelEAgreement_related_quantity "1..1" --> BeModelEAgreement_related
BeModelEAgreement_related_scan "0..1" --> BeModelEAgreement_related
BeModelEAgreement_attachment "0..*" --> BeModelEAgreement
BeModelEAgreement_attachment_kind "1..1" --> BeModelEAgreement_attachment
BeModelEAgreement_attachment_title "0..1" --> BeModelEAgreement_attachment
BeModelEAgreement_attachment_scan "1..1" --> BeModelEAgreement_attachment
@enduml