@startuml
left to right direction
skinparam shadowing false
skinparam nodesep 10
skinparam ranksep 40
skinparam classAttributeIconSize 0
skinparam class {
  FontStyle italic
  BackgroundColor<<rootconcept>> #FAC08F
  BorderColor<<rootconcept>> #E36C0A
  BackgroundColor<<data>> #B8CCE4
  BorderColor<<data>> #4F81BD
  BackgroundColor<<reference>> #D9D9D9
  BorderColor<<reference>> #808080
  BackgroundColor<<value set>> #C3D69B
  BorderColor<<value set>> #77933C
  ArrowColor #4F81BD
}
hide circle
hide empty members

class "BeModelDosagingInformation" as BeModelDosagingInformation <<rootconcept>> {
}

class "timing" as BeModelDosagingInformation_timing <<rootconcept>> {
}

class "event" as BeModelDosagingInformation_timing_event <<data>> {
}

class "code" as BeModelDosagingInformation_timing_code <<data>> {
}

class "doseRange" as BeModelDosagingInformation_doseRange <<data>> {
}

class "doseQuantity" as BeModelDosagingInformation_doseQuantity <<data>> {
}

class "instructions" as BeModelDosagingInformation_instructions <<data>> {
}

class "routeOfAdministration" as BeModelDosagingInformation_routeOfAdministration <<data>> {
}

class "BeRouteOfAdministrationVS" as BeModelDosagingInformation_routeOfAdministration_vs <<value set>> {
}

BeModelDosagingInformation_routeOfAdministration <-- BeModelDosagingInformation_routeOfAdministration_vs
BeModelDosagingInformation_timing "0..1" --> BeModelDosagingInformation
BeModelDosagingInformation_timing_event "0..*" --> BeModelDosagingInformation_timing
BeModelDosagingInformation_timing_code "0..1" --> BeModelDosagingInformation_timing
BeModelDosagingInformation_doseRange "0..1" --> BeModelDosagingInformation
BeModelDosagingInformation_doseQuantity "0..1" --> BeModelDosagingInformation
BeModelDosagingInformation_instructions "0..1" --> BeModelDosagingInformation
BeModelDosagingInformation_routeOfAdministration "0..1" --> BeModelDosagingInformation
@enduml