@startuml
skinparam ClassBackgroundColor #B5E8F7
skinparam linetype polyline
hide circle
hide stereotype

class "**BeModelTreatmentStatus**" as BeModelTreatmentStatus {
|_ identifier 1..1   <<Identifier>>  
|_ startDate 0..1   <<dateTime>>  
|_ endDate 0..1   <<dateTime>>  
|_ status 1..1   <<CodeableConcept>>  
|_ genericRequestId 1..1   <<Reference(BeModelReferralPrescription)>>  
--
}

@enduml