@startuml
skinparam ClassBackgroundColor #B5E8F7
skinparam linetype polyline
hide circle
hide stereotype

class "**BeModelObservationDiabetes**" as BeModelObservationDiabetes {
|_ UniqueIdentifier 1..1   <<Identifier>>  
|_ RecordedDate 1..1   <<dateTime>>  
|_ ObservationPeriod 1..1   <<Period>>  
|_ Patient 1..1   <<Identifier>>  
|_ Recorder 1..1   <<Identifier>>  
|_ Category 1..*   <<CodeableConcept>>  
|_ Status 0..1   <<code>>  
|_ Code 1..1   <<CodeableConcept>>  
|_ Value 1..1   <<Quantity>>  
|_ ReferenceRange 0..*   <<Range>>  
--
}

@enduml