@startuml
skinparam shadowing false
skinparam classAttributeIconSize 0
skinparam linetype ortho
skinparam class {
  BackgroundColor #FEFECE
  BorderColor #000000
  ArrowColor #000000
  FontStyle bold
  AttributeFontStyle normal
}
hide circle
hide empty members

class "BeModelDocument" as BeModelDocument <<model>> {
}

class "identifier" as BeModelDocument_identifier <<Identifier>> {
}

class "type" as BeModelDocument_type <<CodeableConcept>> {
}

class "dateTime" as BeModelDocument_dateTime <<dateTime>> {
}

class "title" as BeModelDocument_title <<string>> {
}

class "status" as BeModelDocument_status <<code>> {
}

class "language" as BeModelDocument_language <<code>> {
}

class "subject" as BeModelDocument_subject <<Reference>> {
}

class "author" as BeModelDocument_author <<Reference>> {
}

class "section" as BeModelDocument_section <<BackboneElement>> {
}

class "code" as BeModelDocument_section_code <<CodeableConcept>> {
}

class "entry" as BeModelDocument_section_entry <<Reference>> {
}

class "section" as BeModelDocument_section_section <<see BeModelDocument.section>> {
}

class "entries" as BeModelDocument_entries <<BackboneElement>> {
}

class "reference" as BeModelDocument_entries_reference <<Reference>> {
}

class "presentedForm" as BeModelDocument_presentedForm <<Attachment>> {
}

BeModelDocument *-- "0..*" BeModelDocument_identifier
BeModelDocument *-- "1..1" BeModelDocument_type
BeModelDocument *-- "1..1" BeModelDocument_dateTime
BeModelDocument *-- "0..1" BeModelDocument_title
BeModelDocument *-- "0..1" BeModelDocument_status
BeModelDocument *-- "0..1" BeModelDocument_language
BeModelDocument *-- "0..1" BeModelDocument_subject
BeModelDocument *-- "0..*" BeModelDocument_author
BeModelDocument *-- "0..*" BeModelDocument_section
BeModelDocument_section *-- "0..1" BeModelDocument_section_code
BeModelDocument_section *-- "0..*" BeModelDocument_section_entry
BeModelDocument_section *-- "0..*" BeModelDocument_section_section
BeModelDocument *-- "0..*" BeModelDocument_entries
BeModelDocument_entries *-- "1..1" BeModelDocument_entries_reference
BeModelDocument *-- "0..*" BeModelDocument_presentedForm
@enduml