@startuml
left to right direction
skinparam shadowing false
skinparam nodesep 10
skinparam ranksep 40
skinparam classAttributeIconSize 0
skinparam class {
  FontStyle italic
  BackgroundColor<<rootconcept>> #FAC08F
  BorderColor<<rootconcept>> #E36C0A
  BackgroundColor<<data>> #B8CCE4
  BorderColor<<data>> #4F81BD
  BackgroundColor<<reference>> #D9D9D9
  BorderColor<<reference>> #808080
  BackgroundColor<<value set>> #C3D69B
  BorderColor<<value set>> #77933C
  ArrowColor #4F81BD
}
hide circle
hide empty members

class "BeModelProblem" as BeModelProblem <<rootconcept>> {
}

class "identifier" as BeModelProblem_identifier <<data>> {
}

class "recordedDate" as BeModelProblem_recordedDate <<data>> {
}

class "recorder" as BeModelProblem_recorder <<data>> {
}

class "asserter" as BeModelProblem_asserter <<data>> {
}

class "subject" as BeModelProblem_subject <<reference>> {
}

class "cause" as BeModelProblem_cause <<reference>> {
}

class "category" as BeModelProblem_category <<data>> {
}

class "ProblemCategoryVS" as BeModelProblem_category_vs <<value set>> {
}

class "code" as BeModelProblem_code <<data>> {
}

class "ProblemCodeVS" as BeModelProblem_code_vs <<value set>> {
}

class "clinicalStatus" as BeModelProblem_clinicalStatus <<data>> {
}

class "condition-clinical" as BeModelProblem_clinicalStatus_vs <<value set>> {
}

class "verificationStatus" as BeModelProblem_verificationStatus <<data>> {
}

class "condition-ver-status" as BeModelProblem_verificationStatus_vs <<value set>> {
}

class "diseaseCourse" as BeModelProblem_diseaseCourse <<data>> {
}

class "ProblemDiseaseCourseVS" as BeModelProblem_diseaseCourse_vs <<value set>> {
}

class "symptom" as BeModelProblem_symptom <<data>> {
}

class "severity" as BeModelProblem_severity <<data>> {
}

class "condition-severity" as BeModelProblem_severity_vs <<value set>> {
}

class "bodySite" as BeModelProblem_bodySite <<rootconcept>> {
}

class "coding" as BeModelProblem_bodySite_coding <<data>> {
}

class "text" as BeModelProblem_bodySite_text <<data>> {
}

class "localisation" as BeModelProblem_bodySite_localisation <<data>> {
}

class "be-vs-bodysite" as BeModelProblem_bodySite_localisation_vs <<value set>> {
}

class "laterality" as BeModelProblem_bodySite_laterality <<data>> {
}

class "be-vs-laterality" as BeModelProblem_bodySite_laterality_vs <<value set>> {
}

class "topography" as BeModelProblem_bodySite_topography <<data>> {
}

class "be-vs-body-topography" as BeModelProblem_bodySite_topography_vs <<value set>> {
}

class "onset[x]" as BeModelProblem_onset_x_ <<data>> {
}

class "abatement[x]" as BeModelProblem_abatement_x_ <<data>> {
}

class "note" as BeModelProblem_note <<data>> {
}

BeModelProblem_category <-- BeModelProblem_category_vs
BeModelProblem_code <-- BeModelProblem_code_vs
BeModelProblem_clinicalStatus <-- BeModelProblem_clinicalStatus_vs
BeModelProblem_verificationStatus <-- BeModelProblem_verificationStatus_vs
BeModelProblem_diseaseCourse <-- BeModelProblem_diseaseCourse_vs
BeModelProblem_severity <-- BeModelProblem_severity_vs
BeModelProblem_bodySite_localisation <-- BeModelProblem_bodySite_localisation_vs
BeModelProblem_bodySite_laterality <-- BeModelProblem_bodySite_laterality_vs
BeModelProblem_bodySite_topography <-- BeModelProblem_bodySite_topography_vs
BeModelProblem_identifier "1..*" --> BeModelProblem
BeModelProblem_recordedDate "1..1" --> BeModelProblem
BeModelProblem_recorder "1..1" --> BeModelProblem
BeModelProblem_asserter "0..1" --> BeModelProblem
BeModelProblem_subject "1..1" --> BeModelProblem
BeModelProblem_cause "0..*" --> BeModelProblem
BeModelProblem_category "0..*" --> BeModelProblem
BeModelProblem_code "1..1" --> BeModelProblem
BeModelProblem_clinicalStatus "1..1" --> BeModelProblem
BeModelProblem_verificationStatus "0..1" --> BeModelProblem
BeModelProblem_diseaseCourse "0..1" --> BeModelProblem
BeModelProblem_symptom "0..*" --> BeModelProblem
BeModelProblem_severity "0..1" --> BeModelProblem
BeModelProblem_bodySite "0..*" --> BeModelProblem
BeModelProblem_bodySite_coding "0..*" --> BeModelProblem_bodySite
BeModelProblem_bodySite_text "0..1" --> BeModelProblem_bodySite
BeModelProblem_bodySite_localisation "1..1" --> BeModelProblem_bodySite
BeModelProblem_bodySite_laterality "0..1" --> BeModelProblem_bodySite
BeModelProblem_bodySite_topography "0..1" --> BeModelProblem_bodySite
BeModelProblem_onset_x_ "0..1" --> BeModelProblem
BeModelProblem_abatement_x_ "0..1" --> BeModelProblem
BeModelProblem_note "0..*" --> BeModelProblem
@enduml