@startuml
left to right direction
skinparam shadowing false
skinparam nodesep 10
skinparam ranksep 40
skinparam classAttributeIconSize 0
skinparam class {
  FontStyle italic
  BackgroundColor<<rootconcept>> #FAC08F
  BorderColor<<rootconcept>> #E36C0A
  BackgroundColor<<data>> #B8CCE4
  BorderColor<<data>> #4F81BD
  BackgroundColor<<reference>> #D9D9D9
  BorderColor<<reference>> #808080
  BackgroundColor<<value set>> #C3D69B
  BorderColor<<value set>> #77933C
  ArrowColor #4F81BD
}
hide circle
hide empty members

class "BeModelVaccinationReduced" as BeModelVaccinationReduced <<rootconcept>> {
}

class "patient" as BeModelVaccinationReduced_patient <<reference>> {
}

class "performer" as BeModelVaccinationReduced_performer <<reference>> {
}

class "administeredProduct" as BeModelVaccinationReduced_administeredProduct <<rootconcept>> {
}

class "product" as BeModelVaccinationReduced_administeredProduct_product <<data>> {
}

class "description" as BeModelVaccinationReduced_administeredProduct_description <<data>> {
}

class "lotNumber" as BeModelVaccinationReduced_administeredProduct_lotNumber <<data>> {
}

class "identifier" as BeModelVaccinationReduced_identifier <<data>> {
}

class "vaccinationDate[x]" as BeModelVaccinationReduced_vaccinationDate_x_ <<data>> {
}

class "recorded" as BeModelVaccinationReduced_recorded <<data>> {
}

class "doseQuantity" as BeModelVaccinationReduced_doseQuantity <<data>> {
}

class "targetDisease" as BeModelVaccinationReduced_targetDisease <<data>> {
}

class "sideEffects" as BeModelVaccinationReduced_sideEffects <<data>> {
}

class "cause" as BeModelVaccinationReduced_cause <<data>> {
}

BeModelVaccinationReduced_patient "1..1" --> BeModelVaccinationReduced
BeModelVaccinationReduced_performer "1..1" --> BeModelVaccinationReduced
BeModelVaccinationReduced_administeredProduct "1..1" --> BeModelVaccinationReduced
BeModelVaccinationReduced_administeredProduct_product "1..1" --> BeModelVaccinationReduced_administeredProduct
BeModelVaccinationReduced_administeredProduct_description "1..1" --> BeModelVaccinationReduced_administeredProduct
BeModelVaccinationReduced_administeredProduct_lotNumber "0..1" --> BeModelVaccinationReduced_administeredProduct
BeModelVaccinationReduced_identifier "0..1" --> BeModelVaccinationReduced
BeModelVaccinationReduced_vaccinationDate_x_ "0..1" --> BeModelVaccinationReduced
BeModelVaccinationReduced_recorded "1..1" --> BeModelVaccinationReduced
BeModelVaccinationReduced_doseQuantity "0..1" --> BeModelVaccinationReduced
BeModelVaccinationReduced_targetDisease "1..1" --> BeModelVaccinationReduced
BeModelVaccinationReduced_sideEffects "0..1" --> BeModelVaccinationReduced
BeModelVaccinationReduced_cause "0..1" --> BeModelVaccinationReduced
@enduml