@startuml
skinparam shadowing false
skinparam classAttributeIconSize 0
skinparam linetype ortho
skinparam class {
  BackgroundColor #FEFECE
  BorderColor #000000
  ArrowColor #000000
  FontStyle bold
  AttributeFontStyle normal
}
hide circle
hide empty members

class "BeModelTreatmentStatus" as BeModelTreatmentStatus <<model>> {
}

class "identifier" as BeModelTreatmentStatus_identifier <<Identifier>> {
}

class "startDate" as BeModelTreatmentStatus_startDate <<dateTime>> {
}

class "endDate" as BeModelTreatmentStatus_endDate <<dateTime>> {
}

class "status" as BeModelTreatmentStatus_status <<CodeableConcept>> {
}

class "genericRequestId" as BeModelTreatmentStatus_genericRequestId <<Reference(BeModelReferralPrescription)>> {
}

BeModelTreatmentStatus *-- "1..1" BeModelTreatmentStatus_identifier
BeModelTreatmentStatus *-- "0..1" BeModelTreatmentStatus_startDate
BeModelTreatmentStatus *-- "0..1" BeModelTreatmentStatus_endDate
BeModelTreatmentStatus *-- "1..1" BeModelTreatmentStatus_status
BeModelTreatmentStatus *-- "1..1" BeModelTreatmentStatus_genericRequestId
@enduml