@startuml
skinparam ClassBackgroundColor #B5E8F7
skinparam linetype polyline
hide circle
hide stereotype

class "**BeModelDocument**" as BeModelDocument {
|_ identifier 0..*   <<Identifier>>  
|_ type 1..1   <<CodeableConcept>>  
|_ dateTime 1..1   <<dateTime>>  
|_ title 0..1   <<string>>  
|_ status 0..1   <<code>>  
|_ language 0..1   <<code>>  
|_ subject 0..1   <<Reference>>  
|_ author 0..*   <<Reference>>  
|_ section 0..*  
  |_ code 0..1   <<CodeableConcept>>  
  |_ entry 0..*   <<Reference>>  
  |_ section 0..*   <<see BeModelDocument.section>>  
|_ entries 0..*  
  |_ reference 1..1   <<Reference>>  
|_ presentedForm 0..*   <<Attachment>>  
--
}

class "**BeModelChildReport**" as BeModelChildReport {
|_ //dateTime// 1..1   <<dateTime>>  
|_ //subject// 1..1   <<Reference>>  
|_ //presentedForm// 1..1   <<Attachment>>  
|_ pregnancyDetails 0..1  
  |_ durationOfPregnancy 0..1  
    |_ subject 1..1   <<Reference>>  
    |_ code 1..1   <<CodeableConcept>>  
    |_ valueInteger 1..1   <<integer>>  
  |_ pregnancyCMVInfection 0..1  
    |_ subject 1..1   <<Reference>>  
    |_ code 1..1   <<CodeableConcept>>  
    |_ valueBoolean 1..1   <<boolean>>  
|_ bacterialMeningitis 0..1  
  |_ code 1..1   <<CodeableConcept>>  
  |_ subject 1..1   <<Reference>>  
  |_ valueBoolean 1..1   <<boolean>>  
|_ neonatalHearingScreeningLeft 0..1  
  |_ date 1..1   <<date>>  
  |_ subject 1..1   <<Reference(be-patient)>>  
  |_ code 1..1   <<CodeableConcept>>  
  |_ valueCode 1..1   <<code>>  
|_ neonatalHearingScreeningRight 0..1  
  |_ date 1..1   <<date>>  
  |_ subject 1..1   <<Reference(be-patient)>>  
  |_ code 1..1   <<CodeableConcept>>  
  |_ valueCode 1..1   <<code>>  
|_ severeHeadTrauma 0..1  
  |_ subject 1..1   <<Reference(be-patient)>>  
  |_ date 1..1   <<date>>  
  |_ code 1..1   <<CodeableConcept>>  
  |_ valueBoolean 1..1   <<boolean>>  
|_ eyeScreening 0..*  
  |_ subject 1..1   <<Reference(be-patient)>>  
  |_ date 1..1   <<date>>  
  |_ code 1..1   <<CodeableConcept>>  
  |_ valueCodeableConcept 1..1   <<code>>  
|_ eyeResults 0..*  
  |_ inspectionPupilAbnormal 0..1  
    |_ subject 1..1   <<Reference(be-patient)>>  
    |_ date 1..1   <<date>>  
    |_ code 1..1   <<CodeableConcept>>  
    |_ valueBoolean 1..1   <<boolean>>  
  |_ eyeMovementAndPosition 0..*  
    |_ subject 1..1   <<Reference(be-patient)>>  
    |_ date 1..1   <<date>>  
    |_ code 1..1   <<CodeableConcept>>  
    |_ valueCode 1..1   <<code>>  
  |_ eyeRemarks 0..1  
    |_ subject 1..1   <<Reference(be-patient)>>  
    |_ date 1..1   <<date>>  
    |_ code 1..1   <<CodeableConcept>>  
    |_ valueString 1..1   <<string>>  
|_ inTreatmentWithOphthalmologist 0..*  
  |_ date 1..1   <<date>>  
  |_ code 1..1   <<CodeableConcept>>  
  |_ valueCode 1..1   <<code>>  
--
}

BeModelDocument <|-- BeModelChildReport
@enduml