@startuml
skinparam ClassBackgroundColor #B5E8F7
skinparam linetype polyline
hide circle
hide stereotype

class "**BeModelMedication**" as BeModelMedication {
|_ status 1..1   <<CodeableConcept>>  
|_ code 1..1   <<CodeableConcept>>  
|_ doseForm 0..1   <<CodeableConcept>>  
|_ item 0..*  
  |_ ingredient 1..*  
    |_ item 1..1   <<CodeableConcept>>  
    |_ role 0..1   <<CodeableConcept>>  
    |_ strength 0..1   <<Ratio>>  
  |_ amount 0..1   <<Quantity>>  
|_ batch 0..1  
  |_ lotNumber 0..1   <<string>>  
  |_ expirationDate 0..1   <<dateTime>>  
--
}

@enduml