@startuml
skinparam shadowing false
skinparam classAttributeIconSize 0
skinparam linetype ortho
skinparam class {
  BackgroundColor #FEFECE
  BorderColor #000000
  ArrowColor #000000
  FontStyle bold
  AttributeFontStyle normal
}
hide circle
hide empty members

class "BeModelGoal" as BeModelGoal {
  +identifier : Identifier [0..*]
  +name : string [1]
  +category : CodeableConcept [1..*]
  +status : code [1]
}

@enduml