@startuml
skinparam ClassBackgroundColor #B5E8F7
skinparam linetype polyline
hide circle
hide stereotype

class "**BeModelDosagingInformation**" as BeModelDosagingInformation {
|_ timing 0..1  
  |_ event 0..*   <<dateTime>>  
  |_ code 0..1   <<CodeableConcept>>  
|_ doseRange 0..1   <<Range>>  
|_ doseQuantity 0..1   <<Quantity>>  
|_ instructions 0..1   <<string>>  
|_ routeOfAdministration 0..1   <<CodeableConcept>>  
--
}

@enduml