@startuml
left to right direction
skinparam shadowing false
skinparam nodesep 10
skinparam ranksep 40
skinparam classAttributeIconSize 0
skinparam class {
  FontStyle italic
  BackgroundColor<<rootconcept>> #FAC08F
  BorderColor<<rootconcept>> #E36C0A
  BackgroundColor<<data>> #B8CCE4
  BorderColor<<data>> #4F81BD
  BackgroundColor<<reference>> #D9D9D9
  BorderColor<<reference>> #808080
  BackgroundColor<<value set>> #C3D69B
  BorderColor<<value set>> #77933C
  ArrowColor #4F81BD
}
hide circle
hide empty members

class "BeModelClinicalObservation" as BeModelClinicalObservation <<rootconcept>> {
}

class "identifier" as BeModelClinicalObservation_identifier <<data>> {
}

class "recordedDate" as BeModelClinicalObservation_recordedDate <<data>> {
}

class "observationDate[x]" as BeModelClinicalObservation_observationDate_x_ <<data>> {
}

class "recorder" as BeModelClinicalObservation_recorder <<reference>> {
}

class "performer" as BeModelClinicalObservation_performer <<reference>> {
}

class "patient" as BeModelClinicalObservation_patient <<reference>> {
}

class "request" as BeModelClinicalObservation_request <<reference>> {
}

class "partOfProcedure" as BeModelClinicalObservation_partOfProcedure <<reference>> {
}

class "specimen" as BeModelClinicalObservation_specimen <<reference>> {
}

class "device" as BeModelClinicalObservation_device <<reference>> {
}

class "category" as BeModelClinicalObservation_category <<data>> {
}

class "code" as BeModelClinicalObservation_code <<data>> {
}

class "value[x]" as BeModelClinicalObservation_value_x_ <<data>> {
}

class "member" as BeModelClinicalObservation_member <<reference>> {
}

class "status" as BeModelClinicalObservation_status <<data>> {
}

class "interpretation" as BeModelClinicalObservation_interpretation <<data>> {
}

class "referenceRange" as BeModelClinicalObservation_referenceRange <<rootconcept>> {
}

class "low" as BeModelClinicalObservation_referenceRange_low <<data>> {
}

class "high" as BeModelClinicalObservation_referenceRange_high <<data>> {
}

class "bodySite" as BeModelClinicalObservation_bodySite <<data>> {
}

class "certainty" as BeModelClinicalObservation_certainty <<data>> {
}

class "note" as BeModelClinicalObservation_note <<data>> {
}

BeModelClinicalObservation_identifier "1..*" --> BeModelClinicalObservation
BeModelClinicalObservation_recordedDate "1..1" --> BeModelClinicalObservation
BeModelClinicalObservation_observationDate_x_ "1..1" --> BeModelClinicalObservation
BeModelClinicalObservation_recorder "1..1" --> BeModelClinicalObservation
BeModelClinicalObservation_performer "0..1" --> BeModelClinicalObservation
BeModelClinicalObservation_patient "1..1" --> BeModelClinicalObservation
BeModelClinicalObservation_request "0..1" --> BeModelClinicalObservation
BeModelClinicalObservation_partOfProcedure "0..*" --> BeModelClinicalObservation
BeModelClinicalObservation_specimen "0..1" --> BeModelClinicalObservation
BeModelClinicalObservation_device "0..1" --> BeModelClinicalObservation
BeModelClinicalObservation_category "0..*" --> BeModelClinicalObservation
BeModelClinicalObservation_code "1..1" --> BeModelClinicalObservation
BeModelClinicalObservation_value_x_ "0..1" --> BeModelClinicalObservation
BeModelClinicalObservation_member "0..*" --> BeModelClinicalObservation
BeModelClinicalObservation_status "1..1" --> BeModelClinicalObservation
BeModelClinicalObservation_interpretation "0..*" --> BeModelClinicalObservation
BeModelClinicalObservation_referenceRange "0..*" --> BeModelClinicalObservation
BeModelClinicalObservation_referenceRange_low "0..1" --> BeModelClinicalObservation_referenceRange
BeModelClinicalObservation_referenceRange_high "0..1" --> BeModelClinicalObservation_referenceRange
BeModelClinicalObservation_bodySite "0..1" --> BeModelClinicalObservation
BeModelClinicalObservation_certainty "0..1" --> BeModelClinicalObservation
BeModelClinicalObservation_note "0..*" --> BeModelClinicalObservation
@enduml