@startuml
skinparam ClassBackgroundColor #B5E8F7
skinparam linetype polyline
hide circle
hide stereotype

class "**BeModelMedicationDispense**" as BeModelMedicationDispense {
|_ identifier 0..*   <<Identifier>>  
|_ recordedDate 0..1   <<dateTime>>  
|_ basedOnMedicationLine 0..1   <<Reference(BeModelMedicationLine)>>  
|_ patient 1..1   <<Reference(be-patient)>>  
|_ status 1..1   <<code>>  
|_ statusReason 0..1   <<CodeableConcept>>  
|_ dispenser 0..1  
  |_ dispenser 0..1   <<Reference(be-practitioner)>>  
  |_ organization 0..1   <<Reference(be-organization)>>  
|_ dispenseDate 1..1   <<dateTime>>  
|_ prescription 0..1  
  |_ isPrescribed 0..1   <<boolean>>  
  |_ prescription 0..1   <<Reference>>  
|_ dispensedItem 1..1  
  |_ product 1..1   <<CodeableConcept>>  
  |_ quantityDispensed 0..1   <<Quantity>>  
  |_ dosage 0..*   <<Dosage>>  
  |_ offLabel 0..1   <<CodeableConcept>>  
|_ note 0..*   <<Annotation>>  
--
}

@enduml