@startuml
left to right direction
skinparam shadowing false
skinparam nodesep 10
skinparam ranksep 40
skinparam classAttributeIconSize 0
skinparam class {
  FontStyle italic
  BackgroundColor<<rootconcept>> #FAC08F
  BorderColor<<rootconcept>> #E36C0A
  BackgroundColor<<data>> #B8CCE4
  BorderColor<<data>> #4F81BD
  BackgroundColor<<reference>> #D9D9D9
  BorderColor<<reference>> #808080
  BackgroundColor<<value set>> #C3D69B
  BorderColor<<value set>> #77933C
  ArrowColor #4F81BD
}
hide circle
hide empty members

class "BeModelMedicationPrescription" as BeModelMedicationPrescription <<rootconcept>> {
}

class "identifier" as BeModelMedicationPrescription_identifier <<data>> {
}

class "recordedDate" as BeModelMedicationPrescription_recordedDate <<data>> {
}

class "basedOnMedicationLine" as BeModelMedicationPrescription_basedOnMedicationLine <<reference>> {
}

class "patient" as BeModelMedicationPrescription_patient <<reference>> {
}

class "status" as BeModelMedicationPrescription_status <<data>> {
}

class "BeMedicationPrescriptionStatusVS" as BeModelMedicationPrescription_status_vs <<value set>> {
}

class "statusReason" as BeModelMedicationPrescription_statusReason <<data>> {
}

class "statusChanged" as BeModelMedicationPrescription_statusChanged <<data>> {
}

class "medication" as BeModelMedicationPrescription_medication <<reference>> {
}

class "prescriber" as BeModelMedicationPrescription_prescriber <<reference>> {
}

class "organization" as BeModelMedicationPrescription_organization <<reference>> {
}

class "indication" as BeModelMedicationPrescription_indication <<rootconcept>> {
}

class "reference" as BeModelMedicationPrescription_indication_reference <<reference>> {
}

class "code" as BeModelMedicationPrescription_indication_code <<data>> {
}

class "dosage" as BeModelMedicationPrescription_dosage <<data>> {
}

class "offLabel" as BeModelMedicationPrescription_offLabel <<rootconcept>> {
}

class "value" as BeModelMedicationPrescription_offLabel_value <<data>> {
}

class "isOffLabelUse" as BeModelMedicationPrescription_offLabel_isOffLabelUse <<data>> {
}

class "reason" as BeModelMedicationPrescription_offLabel_reason <<data>> {
}

class "substitution" as BeModelMedicationPrescription_substitution <<rootconcept>> {
}

class "substitutionAllowed" as BeModelMedicationPrescription_substitution_substitutionAllowed <<data>> {
}

class "instructionForReimbursement" as BeModelMedicationPrescription_instructionForReimbursement <<data>> {
}

class "BeMedicationRequestReimbursementTypeVS" as BeModelMedicationPrescription_instructionForReimbursement_vs <<value set>> {
}

class "validFrom" as BeModelMedicationPrescription_validFrom <<data>> {
}

class "validUntil" as BeModelMedicationPrescription_validUntil <<data>> {
}

class "dispenseRequest" as BeModelMedicationPrescription_dispenseRequest <<rootconcept>> {
}

class "dispenseInterval" as BeModelMedicationPrescription_dispenseRequest_dispenseInterval <<data>> {
}

class "quantityPerDispense" as BeModelMedicationPrescription_dispenseRequest_quantityPerDispense <<data>> {
}

class "note" as BeModelMedicationPrescription_note <<data>> {
}

BeModelMedicationPrescription_status <-- BeModelMedicationPrescription_status_vs
BeModelMedicationPrescription_instructionForReimbursement <-- BeModelMedicationPrescription_instructionForReimbursement_vs
BeModelMedicationPrescription_identifier "1..*" --> BeModelMedicationPrescription
BeModelMedicationPrescription_recordedDate "1..1" --> BeModelMedicationPrescription
BeModelMedicationPrescription_basedOnMedicationLine "0..1" --> BeModelMedicationPrescription
BeModelMedicationPrescription_patient "1..1" --> BeModelMedicationPrescription
BeModelMedicationPrescription_status "1..1" --> BeModelMedicationPrescription
BeModelMedicationPrescription_statusReason "0..1" --> BeModelMedicationPrescription
BeModelMedicationPrescription_statusChanged "0..1" --> BeModelMedicationPrescription
BeModelMedicationPrescription_medication "1..1" --> BeModelMedicationPrescription
BeModelMedicationPrescription_prescriber "1..1" --> BeModelMedicationPrescription
BeModelMedicationPrescription_organization "0..1" --> BeModelMedicationPrescription
BeModelMedicationPrescription_indication "0..*" --> BeModelMedicationPrescription
BeModelMedicationPrescription_indication_reference "0..*" --> BeModelMedicationPrescription_indication
BeModelMedicationPrescription_indication_code "0..*" --> BeModelMedicationPrescription_indication
BeModelMedicationPrescription_dosage "0..*" --> BeModelMedicationPrescription
BeModelMedicationPrescription_offLabel "0..1" --> BeModelMedicationPrescription
BeModelMedicationPrescription_offLabel_value "0..1" --> BeModelMedicationPrescription_offLabel
BeModelMedicationPrescription_offLabel_isOffLabelUse "0..1" --> BeModelMedicationPrescription_offLabel
BeModelMedicationPrescription_offLabel_reason "1..1" --> BeModelMedicationPrescription_offLabel
BeModelMedicationPrescription_substitution "0..1" --> BeModelMedicationPrescription
BeModelMedicationPrescription_substitution_substitutionAllowed "1..1" --> BeModelMedicationPrescription_substitution
BeModelMedicationPrescription_instructionForReimbursement "0..1" --> BeModelMedicationPrescription
BeModelMedicationPrescription_validFrom "1..1" --> BeModelMedicationPrescription
BeModelMedicationPrescription_validUntil "0..1" --> BeModelMedicationPrescription
BeModelMedicationPrescription_dispenseRequest "0..1" --> BeModelMedicationPrescription
BeModelMedicationPrescription_dispenseRequest_dispenseInterval "0..1" --> BeModelMedicationPrescription_dispenseRequest
BeModelMedicationPrescription_dispenseRequest_quantityPerDispense "0..1" --> BeModelMedicationPrescription_dispenseRequest
BeModelMedicationPrescription_note "0..*" --> BeModelMedicationPrescription
@enduml