@startuml
skinparam shadowing false
skinparam classAttributeIconSize 0
skinparam linetype ortho
skinparam class {
  BackgroundColor #FEFECE
  BorderColor #000000
  ArrowColor #000000
  FontStyle bold
  AttributeFontStyle normal
}
hide circle
hide empty members

class "BeModelVaccination" as BeModelVaccination <<model>> {
}

class "recorded" as BeModelVaccination_recorded <<dateTime>> {
}

class "patient" as BeModelVaccination_patient <<Reference(Patient)>> {
}

class "vaccinationRequest" as BeModelVaccination_vaccinationRequest <<Reference>> {
}

class "recorder" as BeModelVaccination_recorder <<Reference(Practitioner)>> {
}

class "performer" as BeModelVaccination_performer <<Reference(Practitioner)>> {
}

class "vaccineCode" as BeModelVaccination_vaccineCode <<CodeableConcept>> {
}

class "vaccinationDate[x]" as BeModelVaccination_vaccinationDate_x_ <<dateTime | string>> {
}

class "administeredProduct" as BeModelVaccination_administeredProduct <<BackboneElement>> {
}

class "product[x]" as BeModelVaccination_administeredProduct_product_x_ <<Reference | CodeableConcept>> {
}

class "lotNumber" as BeModelVaccination_administeredProduct_lotNumber <<string>> {
}

class "expirationDate" as BeModelVaccination_administeredProduct_expirationDate <<date>> {
}

class "route" as BeModelVaccination_route <<CodeableConcept>> {
}

class "status" as BeModelVaccination_status <<code>> {
}

class "statusReason" as BeModelVaccination_statusReason <<CodeableConcept>> {
  be-vs-vaccination-status-reason
}

class "reaction" as BeModelVaccination_reaction <<BackboneElement>> {
}

class "reactionDate" as BeModelVaccination_reaction_reactionDate <<dateTime>> {
}

class "manifestation" as BeModelVaccination_reaction_manifestation <<Reference>> {
}

class "doseQuantity" as BeModelVaccination_doseQuantity <<BackboneElement>> {
}

class "note" as BeModelVaccination_note <<Attachment>> {
}

class "site" as BeModelVaccination_site <<CodeableConcept>> {
}

class "identifier" as BeModelVaccination_identifier <<Identifier>> {
}

class "bodyLaterality" as BeModelVaccination_bodyLaterality <<CodeableConcept>> {
}

class "location" as BeModelVaccination_location <<Reference>> {
}

class "locationType" as BeModelVaccination_locationType <<CodeableConcept>> {
}

class "cause" as BeModelVaccination_cause <<CodeableConcept>> {
}

class "stockOrigin" as BeModelVaccination_stockOrigin <<Reference(Location)>> {
}

class "stockFundingEntity" as BeModelVaccination_stockFundingEntity <<Reference(Organization)>> {
}

BeModelVaccination *-- "1..1" BeModelVaccination_recorded
BeModelVaccination *-- "1..1" BeModelVaccination_patient
BeModelVaccination *-- "0..1" BeModelVaccination_vaccinationRequest
BeModelVaccination *-- "1..1" BeModelVaccination_recorder
BeModelVaccination *-- "0..1" BeModelVaccination_performer
BeModelVaccination *-- "1..1" BeModelVaccination_vaccineCode
BeModelVaccination *-- "0..1" BeModelVaccination_vaccinationDate_x_
BeModelVaccination *-- "0..1" BeModelVaccination_administeredProduct
BeModelVaccination_administeredProduct *-- "0..1" BeModelVaccination_administeredProduct_product_x_
BeModelVaccination_administeredProduct *-- "0..1" BeModelVaccination_administeredProduct_lotNumber
BeModelVaccination_administeredProduct *-- "0..1" BeModelVaccination_administeredProduct_expirationDate
BeModelVaccination *-- "0..1" BeModelVaccination_route
BeModelVaccination *-- "1..1" BeModelVaccination_status
BeModelVaccination *-- "0..1" BeModelVaccination_statusReason
BeModelVaccination *-- "0..1" BeModelVaccination_reaction
BeModelVaccination_reaction *-- "1..1" BeModelVaccination_reaction_reactionDate
BeModelVaccination_reaction *-- "0..1" BeModelVaccination_reaction_manifestation
BeModelVaccination *-- "0..1" BeModelVaccination_doseQuantity
BeModelVaccination *-- "0..1" BeModelVaccination_note
BeModelVaccination *-- "1..1" BeModelVaccination_site
BeModelVaccination *-- "0..*" BeModelVaccination_identifier
BeModelVaccination *-- "0..1" BeModelVaccination_bodyLaterality
BeModelVaccination *-- "0..1" BeModelVaccination_location
BeModelVaccination *-- "0..1" BeModelVaccination_locationType
BeModelVaccination *-- "0..1" BeModelVaccination_cause
BeModelVaccination *-- "0..1" BeModelVaccination_stockOrigin
BeModelVaccination *-- "0..1" BeModelVaccination_stockFundingEntity
@enduml