@startuml
skinparam ClassBackgroundColor #B5E8F7
skinparam linetype polyline
hide circle
hide stereotype

class "**BeModelAllergyIntolerance**" as BeModelAllergyIntolerance {
|_ patient 1..1   <<Reference>>  
|_ code 1..1   <<CodeableConcept>>  
|_ category 0..*   <<code>>  
|_ type 0..1   <<code>>  
|_ status 0..1  
  |_ clinicalStatus 1..1   <<CodeableConcept>>  
  |_ verificationStatus 1..1   <<CodeableConcept>>  
|_ recordedDate 1..1   <<dateTime>>  
|_ recorder 1..1   <<Reference>>  
|_ asserter 0..1   <<Reference>>  
|_ note 0..1   <<string>>  
|_ reactions 0..*  
  |_ manifestation 1..1   <<CodeableConcept>>  
  |_ onset 0..1   <<dateTime>>  
  |_ note 0..1   <<string>>  
--
}

@enduml