@startuml
skinparam shadowing false
skinparam classAttributeIconSize 0
skinparam linetype ortho
skinparam class {
  BackgroundColor #FEFECE
  BorderColor #000000
  ArrowColor #000000
  FontStyle bold
  AttributeFontStyle normal
}
hide circle
hide empty members

class "BeModelPatientDocument" as BeModelPatientDocument <<model>> {
}

class "patient" as BeModelPatientDocument_patient <<Identifier>> {
}

class "author" as BeModelPatientDocument_author <<Identifier>> {
}

class "category" as BeModelPatientDocument_category <<CodeableConcept>> {
}

class "document" as BeModelPatientDocument_document <<BackboneElement>> {
}

class "content" as BeModelPatientDocument_document_content <<Binary>> {
}

class "mimetype" as BeModelPatientDocument_document_mimetype <<string>> {
}

class "url" as BeModelPatientDocument_document_url <<uri>> {
}

class "context" as BeModelPatientDocument_context <<Element>> {
}

BeModelPatientDocument *-- "1..1" BeModelPatientDocument_patient
BeModelPatientDocument *-- "1..1" BeModelPatientDocument_author
BeModelPatientDocument *-- "0..*" BeModelPatientDocument_category
BeModelPatientDocument *-- "1..1" BeModelPatientDocument_document
BeModelPatientDocument_document *-- "0..1" BeModelPatientDocument_document_content
BeModelPatientDocument_document *-- "1..1" BeModelPatientDocument_document_mimetype
BeModelPatientDocument_document *-- "0..1" BeModelPatientDocument_document_url
BeModelPatientDocument *-- "0..*" BeModelPatientDocument_context
@enduml