@startuml
left to right direction
skinparam shadowing false
skinparam nodesep 10
skinparam ranksep 40
skinparam classAttributeIconSize 0
skinparam class {
  FontStyle italic
  BackgroundColor<<rootconcept>> #FAC08F
  BorderColor<<rootconcept>> #E36C0A
  BackgroundColor<<data>> #B8CCE4
  BorderColor<<data>> #4F81BD
  BackgroundColor<<reference>> #D9D9D9
  BorderColor<<reference>> #808080
  BackgroundColor<<value set>> #C3D69B
  BorderColor<<value set>> #77933C
  ArrowColor #4F81BD
}
hide circle
hide empty members

class "BeModelGoal" as BeModelGoal <<rootconcept>> {
}

class "identifier" as BeModelGoal_identifier <<data>> {
}

class "name" as BeModelGoal_name <<data>> {
}

class "category" as BeModelGoal_category <<data>> {
}

class "status" as BeModelGoal_status <<data>> {
}

BeModelGoal_identifier "0..*" --> BeModelGoal
BeModelGoal_name "1..1" --> BeModelGoal
BeModelGoal_category "1..*" --> BeModelGoal
BeModelGoal_status "1..1" --> BeModelGoal
@enduml