@startuml
skinparam shadowing false
skinparam classAttributeIconSize 0
skinparam linetype ortho
skinparam class {
  BackgroundColor #FEFECE
  BorderColor #000000
  ArrowColor #000000
  FontStyle bold
  AttributeFontStyle normal
}
hide circle
hide empty members

class "BeModelGoal" as BeModelGoal <<model>> {
}

class "identifier" as BeModelGoal_identifier <<Identifier>> {
}

class "name" as BeModelGoal_name <<string>> {
}

class "category" as BeModelGoal_category <<CodeableConcept>> {
}

class "status" as BeModelGoal_status <<code>> {
}

BeModelGoal *-- "0..*" BeModelGoal_identifier
BeModelGoal *-- "1..1" BeModelGoal_name
BeModelGoal *-- "1..*" BeModelGoal_category
BeModelGoal *-- "1..1" BeModelGoal_status
@enduml