@startuml
skinparam shadowing false
skinparam classAttributeIconSize 0
skinparam linetype ortho
skinparam class {
  BackgroundColor #FEFECE
  BorderColor #000000
  ArrowColor #000000
  FontStyle bold
  AttributeFontStyle normal
}
hide circle
hide empty members

class "BeModelCarePlan" as BeModelCarePlan {
  +identifier : Identifier [0..*]
  +name : string [0..1]
  +category : CodeableConcept [0..*]
  +basedOn : Reference [0..*]
  +partOf : Reference [0..*]
  +status : code [0..1]
  +description : string [0..1]
  +instantiates : Reference [0..*]
  +subject : Reference [0..1]
  +period : Period [0..1]
  +author : Reference [0..*]
  +careTeam : Reference [0..*]
  +goal : Reference [0..*]
  +managingOrganization : Reference [0..1]
  +contact : ContactPoint [0..*]
  +note : string [0..*]
}

class "BeModelCarePlan.participant" as BeModelCarePlan_participant {
  +role : CodeableConcept [0..1]
  +member : Reference [1]
  +period : Period [0..1]
}

BeModelCarePlan *-- "0..*" BeModelCarePlan_participant : participant
@enduml