@startuml
skinparam shadowing false
skinparam classAttributeIconSize 0
skinparam linetype ortho
skinparam class {
  BackgroundColor #FEFECE
  BorderColor #000000
  ArrowColor #000000
  FontStyle bold
  AttributeFontStyle normal
}
hide circle
hide empty members

class "BeModelCareTeam" as BeModelCareTeam <<model>> {
}

class "name" as BeModelCareTeam_name <<string>> {
}

class "identifier" as BeModelCareTeam_identifier <<Identifier>> {
}

class "category" as BeModelCareTeam_category <<CodeableConcept>> {
}

class "status" as BeModelCareTeam_status <<code>> {
}

class "subject" as BeModelCareTeam_subject <<Reference>> {
}

class "period" as BeModelCareTeam_period <<Period>> {
}

class "participant" as BeModelCareTeam_participant <<BackboneElement>> {
}

class "role" as BeModelCareTeam_participant_role <<CodeableConcept>> {
}

class "member" as BeModelCareTeam_participant_member <<Reference>> {
}

class "period" as BeModelCareTeam_participant_period <<Period>> {
}

class "managingOrganization" as BeModelCareTeam_managingOrganization <<Reference>> {
}

class "contact" as BeModelCareTeam_contact <<ContactPoint>> {
}

class "note" as BeModelCareTeam_note <<string>> {
}

BeModelCareTeam *-- "0..1" BeModelCareTeam_name
BeModelCareTeam *-- "0..*" BeModelCareTeam_identifier
BeModelCareTeam *-- "0..*" BeModelCareTeam_category
BeModelCareTeam *-- "0..1" BeModelCareTeam_status
BeModelCareTeam *-- "0..1" BeModelCareTeam_subject
BeModelCareTeam *-- "0..1" BeModelCareTeam_period
BeModelCareTeam *-- "0..*" BeModelCareTeam_participant
BeModelCareTeam_participant *-- "0..1" BeModelCareTeam_participant_role
BeModelCareTeam_participant *-- "1..1" BeModelCareTeam_participant_member
BeModelCareTeam_participant *-- "0..1" BeModelCareTeam_participant_period
BeModelCareTeam *-- "0..1" BeModelCareTeam_managingOrganization
BeModelCareTeam *-- "0..*" BeModelCareTeam_contact
BeModelCareTeam *-- "0..*" BeModelCareTeam_note
@enduml