@startuml
skinparam shadowing false
skinparam classAttributeIconSize 0
skinparam linetype ortho
skinparam class {
  BackgroundColor #FEFECE
  BorderColor #000000
  ArrowColor #000000
  FontStyle bold
  AttributeFontStyle normal
}
hide circle
hide empty members

class "BeModelMedication" as BeModelMedication <<model>> {
}

class "status" as BeModelMedication_status <<CodeableConcept>> {
}

class "code" as BeModelMedication_code <<CodeableConcept>> {
}

class "doseForm" as BeModelMedication_doseForm <<CodeableConcept>> {
}

class "item" as BeModelMedication_item <<BackboneElement>> {
}

class "ingredient" as BeModelMedication_item_ingredient <<BackboneElement>> {
}

class "item" as BeModelMedication_item_ingredient_item <<CodeableConcept>> {
}

class "role" as BeModelMedication_item_ingredient_role <<CodeableConcept>> {
}

class "strength" as BeModelMedication_item_ingredient_strength <<Ratio>> {
}

class "amount" as BeModelMedication_item_amount <<Quantity>> {
}

class "batch" as BeModelMedication_batch <<BackboneElement>> {
}

class "lotNumber" as BeModelMedication_batch_lotNumber <<string>> {
}

class "expirationDate" as BeModelMedication_batch_expirationDate <<dateTime>> {
}

BeModelMedication *-- "1..1" BeModelMedication_status
BeModelMedication *-- "1..1" BeModelMedication_code
BeModelMedication *-- "0..1" BeModelMedication_doseForm
BeModelMedication *-- "0..*" BeModelMedication_item
BeModelMedication_item *-- "1..*" BeModelMedication_item_ingredient
BeModelMedication_item_ingredient *-- "1..1" BeModelMedication_item_ingredient_item
BeModelMedication_item_ingredient *-- "0..1" BeModelMedication_item_ingredient_role
BeModelMedication_item_ingredient *-- "0..1" BeModelMedication_item_ingredient_strength
BeModelMedication_item *-- "0..1" BeModelMedication_item_amount
BeModelMedication *-- "0..1" BeModelMedication_batch
BeModelMedication_batch *-- "0..1" BeModelMedication_batch_lotNumber
BeModelMedication_batch *-- "0..1" BeModelMedication_batch_expirationDate
@enduml