@startuml
skinparam ClassBackgroundColor #B5E8F7
skinparam linetype polyline
hide circle
hide stereotype

class "**BeModelCareTeam**" as BeModelCareTeam {
|_ name 0..1   <<string>>  
|_ identifier 0..*   <<Identifier>>  
|_ category 0..*   <<CodeableConcept>>  
|_ status 0..1   <<code>>  
|_ subject 0..1   <<Reference>>  
|_ period 0..1   <<Period>>  
|_ participant 0..*  
  |_ role 0..1   <<CodeableConcept>>  
  |_ member 1..1   <<Reference>>  
  |_ period 0..1   <<Period>>  
|_ managingOrganization 0..1   <<Reference>>  
|_ contact 0..*   <<ContactPoint>>  
|_ note 0..*   <<string>>  
--
}

@enduml