@startuml
skinparam shadowing false
skinparam classAttributeIconSize 0
skinparam linetype ortho
skinparam class {
  BackgroundColor #FEFECE
  BorderColor #000000
  ArrowColor #000000
  FontStyle bold
  AttributeFontStyle normal
}
hide circle
hide empty members

class "BeModelOrganisationClaim" as BeModelOrganisationClaim <<model>> {
}

class "identifier" as BeModelOrganisationClaim_identifier <<Identifier>> {
}

class "intent" as BeModelOrganisationClaim_intent <<CodeableConcept>> {
}

class "status" as BeModelOrganisationClaim_status <<CodeableConcept>> {
}

class "treatmentStatusId" as BeModelOrganisationClaim_treatmentStatusId <<Reference(BeModelTreatmentStatus)>> {
}

class "focus" as BeModelOrganisationClaim_focus <<Reference(BeModelReferralPrescription)>> {
}

class "organization" as BeModelOrganisationClaim_organization <<Identifier>> {
}

BeModelOrganisationClaim *-- "1..1" BeModelOrganisationClaim_identifier
BeModelOrganisationClaim *-- "1..1" BeModelOrganisationClaim_intent
BeModelOrganisationClaim *-- "1..1" BeModelOrganisationClaim_status
BeModelOrganisationClaim *-- "1..1" BeModelOrganisationClaim_treatmentStatusId
BeModelOrganisationClaim *-- "1..1" BeModelOrganisationClaim_focus
BeModelOrganisationClaim *-- "1..1" BeModelOrganisationClaim_organization
@enduml