@startuml
left to right direction
skinparam shadowing false
skinparam nodesep 10
skinparam ranksep 40
skinparam classAttributeIconSize 0
skinparam class {
  FontStyle italic
  BackgroundColor<<rootconcept>> #FAC08F
  BorderColor<<rootconcept>> #E36C0A
  BackgroundColor<<data>> #B8CCE4
  BorderColor<<data>> #4F81BD
  BackgroundColor<<reference>> #D9D9D9
  BorderColor<<reference>> #808080
  BackgroundColor<<value set>> #C3D69B
  BorderColor<<value set>> #77933C
  ArrowColor #4F81BD
}
hide circle
hide empty members

class "BeModelDocument" as BeModelDocument <<rootconcept>> {
}

class "identifier" as BeModelDocument_identifier <<data>> {
}

class "type" as BeModelDocument_type <<data>> {
}

class "dateTime" as BeModelDocument_dateTime <<data>> {
}

class "title" as BeModelDocument_title <<data>> {
}

class "status" as BeModelDocument_status <<data>> {
}

class "language" as BeModelDocument_language <<data>> {
}

class "subject" as BeModelDocument_subject <<reference>> {
}

class "author" as BeModelDocument_author <<reference>> {
}

class "section" as BeModelDocument_section <<rootconcept>> {
}

class "code" as BeModelDocument_section_code <<data>> {
}

class "entry" as BeModelDocument_section_entry <<reference>> {
}

class "section" as BeModelDocument_section_section <<data>> {
}

class "entries" as BeModelDocument_entries <<rootconcept>> {
}

class "reference" as BeModelDocument_entries_reference <<reference>> {
}

class "presentedForm" as BeModelDocument_presentedForm <<data>> {
}

class "BeModelChildReport" as BeModelChildReport <<rootconcept>> {
}

class "dateTime" as BeModelChildReport_dateTime <<data>> {
}

class "subject" as BeModelChildReport_subject <<reference>> {
}

class "presentedForm" as BeModelChildReport_presentedForm <<data>> {
}

class "pregnancyDetails" as BeModelChildReport_pregnancyDetails <<rootconcept>> {
}

class "durationOfPregnancy" as BeModelChildReport_pregnancyDetails_durationOfPregnancy <<rootconcept>> {
}

class "subject" as BeModelChildReport_pregnancyDetails_durationOfPregnancy_subject <<reference>> {
}

class "code" as BeModelChildReport_pregnancyDetails_durationOfPregnancy_code <<data>> {
}

class "valueInteger" as BeModelChildReport_pregnancyDetails_durationOfPregnancy_valueInteger <<data>> {
}

class "pregnancyCMVInfection" as BeModelChildReport_pregnancyDetails_pregnancyCMVInfection <<rootconcept>> {
}

class "subject" as BeModelChildReport_pregnancyDetails_pregnancyCMVInfection_subject <<reference>> {
}

class "code" as BeModelChildReport_pregnancyDetails_pregnancyCMVInfection_code <<data>> {
}

class "valueBoolean" as BeModelChildReport_pregnancyDetails_pregnancyCMVInfection_valueBoolean <<data>> {
}

class "bacterialMeningitis" as BeModelChildReport_bacterialMeningitis <<rootconcept>> {
}

class "code" as BeModelChildReport_bacterialMeningitis_code <<data>> {
}

class "subject" as BeModelChildReport_bacterialMeningitis_subject <<reference>> {
}

class "valueBoolean" as BeModelChildReport_bacterialMeningitis_valueBoolean <<data>> {
}

class "neonatalHearingScreeningLeft" as BeModelChildReport_neonatalHearingScreeningLeft <<rootconcept>> {
}

class "date" as BeModelChildReport_neonatalHearingScreeningLeft_date <<data>> {
}

class "subject" as BeModelChildReport_neonatalHearingScreeningLeft_subject <<reference>> {
}

class "code" as BeModelChildReport_neonatalHearingScreeningLeft_code <<data>> {
}

class "valueCode" as BeModelChildReport_neonatalHearingScreeningLeft_valueCode <<data>> {
}

class "vs-neonatal-hearing-screening-results" as BeModelChildReport_neonatalHearingScreeningLeft_valueCode_vs <<value set>> {
}

class "neonatalHearingScreeningRight" as BeModelChildReport_neonatalHearingScreeningRight <<rootconcept>> {
}

class "date" as BeModelChildReport_neonatalHearingScreeningRight_date <<data>> {
}

class "subject" as BeModelChildReport_neonatalHearingScreeningRight_subject <<reference>> {
}

class "code" as BeModelChildReport_neonatalHearingScreeningRight_code <<data>> {
}

class "valueCode" as BeModelChildReport_neonatalHearingScreeningRight_valueCode <<data>> {
}

class "vs-neonatal-hearing-screening-results" as BeModelChildReport_neonatalHearingScreeningRight_valueCode_vs <<value set>> {
}

class "severeHeadTrauma" as BeModelChildReport_severeHeadTrauma <<rootconcept>> {
}

class "subject" as BeModelChildReport_severeHeadTrauma_subject <<reference>> {
}

class "date" as BeModelChildReport_severeHeadTrauma_date <<data>> {
}

class "code" as BeModelChildReport_severeHeadTrauma_code <<data>> {
}

class "valueBoolean" as BeModelChildReport_severeHeadTrauma_valueBoolean <<data>> {
}

class "eyeScreening" as BeModelChildReport_eyeScreening <<rootconcept>> {
}

class "subject" as BeModelChildReport_eyeScreening_subject <<reference>> {
}

class "date" as BeModelChildReport_eyeScreening_date <<data>> {
}

class "code" as BeModelChildReport_eyeScreening_code <<data>> {
}

class "valueCodeableConcept" as BeModelChildReport_eyeScreening_valueCodeableConcept <<data>> {
}

class "vs-eye-screening-results" as BeModelChildReport_eyeScreening_valueCodeableConcept_vs <<value set>> {
}

class "eyeResults" as BeModelChildReport_eyeResults <<rootconcept>> {
}

class "inspectionPupilAbnormal" as BeModelChildReport_eyeResults_inspectionPupilAbnormal <<rootconcept>> {
}

class "subject" as BeModelChildReport_eyeResults_inspectionPupilAbnormal_subject <<reference>> {
}

class "date" as BeModelChildReport_eyeResults_inspectionPupilAbnormal_date <<data>> {
}

class "code" as BeModelChildReport_eyeResults_inspectionPupilAbnormal_code <<data>> {
}

class "valueBoolean" as BeModelChildReport_eyeResults_inspectionPupilAbnormal_valueBoolean <<data>> {
}

class "eyeMovementAndPosition" as BeModelChildReport_eyeResults_eyeMovementAndPosition <<rootconcept>> {
}

class "subject" as BeModelChildReport_eyeResults_eyeMovementAndPosition_subject <<reference>> {
}

class "date" as BeModelChildReport_eyeResults_eyeMovementAndPosition_date <<data>> {
}

class "code" as BeModelChildReport_eyeResults_eyeMovementAndPosition_code <<data>> {
}

class "valueCode" as BeModelChildReport_eyeResults_eyeMovementAndPosition_valueCode <<data>> {
}

class "vs-eye-movement-and-position" as BeModelChildReport_eyeResults_eyeMovementAndPosition_valueCode_vs <<value set>> {
}

class "eyeRemarks" as BeModelChildReport_eyeResults_eyeRemarks <<rootconcept>> {
}

class "subject" as BeModelChildReport_eyeResults_eyeRemarks_subject <<reference>> {
}

class "date" as BeModelChildReport_eyeResults_eyeRemarks_date <<data>> {
}

class "code" as BeModelChildReport_eyeResults_eyeRemarks_code <<data>> {
}

class "valueString" as BeModelChildReport_eyeResults_eyeRemarks_valueString <<data>> {
}

class "inTreatmentWithOphthalmologist" as BeModelChildReport_inTreatmentWithOphthalmologist <<rootconcept>> {
}

class "date" as BeModelChildReport_inTreatmentWithOphthalmologist_date <<data>> {
}

class "code" as BeModelChildReport_inTreatmentWithOphthalmologist_code <<data>> {
}

class "valueCode" as BeModelChildReport_inTreatmentWithOphthalmologist_valueCode <<data>> {
}

class "vs-ophthalmologist-treatments" as BeModelChildReport_inTreatmentWithOphthalmologist_valueCode_vs <<value set>> {
}

BeModelDocument_identifier "0..*" --> BeModelDocument
BeModelDocument_type "1..1" --> BeModelDocument
BeModelDocument_dateTime "1..1" --> BeModelDocument
BeModelDocument_title "0..1" --> BeModelDocument
BeModelDocument_status "0..1" --> BeModelDocument
BeModelDocument_language "0..1" --> BeModelDocument
BeModelDocument_subject "0..1" --> BeModelDocument
BeModelDocument_author "0..*" --> BeModelDocument
BeModelDocument_section "0..*" --> BeModelDocument
BeModelDocument_section_code "0..1" --> BeModelDocument_section
BeModelDocument_section_entry "0..*" --> BeModelDocument_section
BeModelDocument_section_section "0..*" --> BeModelDocument_section
BeModelDocument_entries "0..*" --> BeModelDocument
BeModelDocument_entries_reference "1..1" --> BeModelDocument_entries
BeModelDocument_presentedForm "0..*" --> BeModelDocument
BeModelChildReport_neonatalHearingScreeningLeft_valueCode <-- BeModelChildReport_neonatalHearingScreeningLeft_valueCode_vs
BeModelChildReport_neonatalHearingScreeningRight_valueCode <-- BeModelChildReport_neonatalHearingScreeningRight_valueCode_vs
BeModelChildReport_eyeScreening_valueCodeableConcept <-- BeModelChildReport_eyeScreening_valueCodeableConcept_vs
BeModelChildReport_eyeResults_eyeMovementAndPosition_valueCode <-- BeModelChildReport_eyeResults_eyeMovementAndPosition_valueCode_vs
BeModelChildReport_inTreatmentWithOphthalmologist_valueCode <-- BeModelChildReport_inTreatmentWithOphthalmologist_valueCode_vs
BeModelChildReport_dateTime "1..1" --> BeModelChildReport
BeModelChildReport_subject "1..1" --> BeModelChildReport
BeModelChildReport_presentedForm "1..1" --> BeModelChildReport
BeModelChildReport_pregnancyDetails "0..1" --> BeModelChildReport
BeModelChildReport_pregnancyDetails_durationOfPregnancy "0..1" --> BeModelChildReport_pregnancyDetails
BeModelChildReport_pregnancyDetails_durationOfPregnancy_subject "1..1" --> BeModelChildReport_pregnancyDetails_durationOfPregnancy
BeModelChildReport_pregnancyDetails_durationOfPregnancy_code "1..1" --> BeModelChildReport_pregnancyDetails_durationOfPregnancy
BeModelChildReport_pregnancyDetails_durationOfPregnancy_valueInteger "1..1" --> BeModelChildReport_pregnancyDetails_durationOfPregnancy
BeModelChildReport_pregnancyDetails_pregnancyCMVInfection "0..1" --> BeModelChildReport_pregnancyDetails
BeModelChildReport_pregnancyDetails_pregnancyCMVInfection_subject "1..1" --> BeModelChildReport_pregnancyDetails_pregnancyCMVInfection
BeModelChildReport_pregnancyDetails_pregnancyCMVInfection_code "1..1" --> BeModelChildReport_pregnancyDetails_pregnancyCMVInfection
BeModelChildReport_pregnancyDetails_pregnancyCMVInfection_valueBoolean "1..1" --> BeModelChildReport_pregnancyDetails_pregnancyCMVInfection
BeModelChildReport_bacterialMeningitis "0..1" --> BeModelChildReport
BeModelChildReport_bacterialMeningitis_code "1..1" --> BeModelChildReport_bacterialMeningitis
BeModelChildReport_bacterialMeningitis_subject "1..1" --> BeModelChildReport_bacterialMeningitis
BeModelChildReport_bacterialMeningitis_valueBoolean "1..1" --> BeModelChildReport_bacterialMeningitis
BeModelChildReport_neonatalHearingScreeningLeft "0..1" --> BeModelChildReport
BeModelChildReport_neonatalHearingScreeningLeft_date "1..1" --> BeModelChildReport_neonatalHearingScreeningLeft
BeModelChildReport_neonatalHearingScreeningLeft_subject "1..1" --> BeModelChildReport_neonatalHearingScreeningLeft
BeModelChildReport_neonatalHearingScreeningLeft_code "1..1" --> BeModelChildReport_neonatalHearingScreeningLeft
BeModelChildReport_neonatalHearingScreeningLeft_valueCode "1..1" --> BeModelChildReport_neonatalHearingScreeningLeft
BeModelChildReport_neonatalHearingScreeningRight "0..1" --> BeModelChildReport
BeModelChildReport_neonatalHearingScreeningRight_date "1..1" --> BeModelChildReport_neonatalHearingScreeningRight
BeModelChildReport_neonatalHearingScreeningRight_subject "1..1" --> BeModelChildReport_neonatalHearingScreeningRight
BeModelChildReport_neonatalHearingScreeningRight_code "1..1" --> BeModelChildReport_neonatalHearingScreeningRight
BeModelChildReport_neonatalHearingScreeningRight_valueCode "1..1" --> BeModelChildReport_neonatalHearingScreeningRight
BeModelChildReport_severeHeadTrauma "0..1" --> BeModelChildReport
BeModelChildReport_severeHeadTrauma_subject "1..1" --> BeModelChildReport_severeHeadTrauma
BeModelChildReport_severeHeadTrauma_date "1..1" --> BeModelChildReport_severeHeadTrauma
BeModelChildReport_severeHeadTrauma_code "1..1" --> BeModelChildReport_severeHeadTrauma
BeModelChildReport_severeHeadTrauma_valueBoolean "1..1" --> BeModelChildReport_severeHeadTrauma
BeModelChildReport_eyeScreening "0..*" --> BeModelChildReport
BeModelChildReport_eyeScreening_subject "1..1" --> BeModelChildReport_eyeScreening
BeModelChildReport_eyeScreening_date "1..1" --> BeModelChildReport_eyeScreening
BeModelChildReport_eyeScreening_code "1..1" --> BeModelChildReport_eyeScreening
BeModelChildReport_eyeScreening_valueCodeableConcept "1..1" --> BeModelChildReport_eyeScreening
BeModelChildReport_eyeResults "0..*" --> BeModelChildReport
BeModelChildReport_eyeResults_inspectionPupilAbnormal "0..1" --> BeModelChildReport_eyeResults
BeModelChildReport_eyeResults_inspectionPupilAbnormal_subject "1..1" --> BeModelChildReport_eyeResults_inspectionPupilAbnormal
BeModelChildReport_eyeResults_inspectionPupilAbnormal_date "1..1" --> BeModelChildReport_eyeResults_inspectionPupilAbnormal
BeModelChildReport_eyeResults_inspectionPupilAbnormal_code "1..1" --> BeModelChildReport_eyeResults_inspectionPupilAbnormal
BeModelChildReport_eyeResults_inspectionPupilAbnormal_valueBoolean "1..1" --> BeModelChildReport_eyeResults_inspectionPupilAbnormal
BeModelChildReport_eyeResults_eyeMovementAndPosition "0..*" --> BeModelChildReport_eyeResults
BeModelChildReport_eyeResults_eyeMovementAndPosition_subject "1..1" --> BeModelChildReport_eyeResults_eyeMovementAndPosition
BeModelChildReport_eyeResults_eyeMovementAndPosition_date "1..1" --> BeModelChildReport_eyeResults_eyeMovementAndPosition
BeModelChildReport_eyeResults_eyeMovementAndPosition_code "1..1" --> BeModelChildReport_eyeResults_eyeMovementAndPosition
BeModelChildReport_eyeResults_eyeMovementAndPosition_valueCode "1..1" --> BeModelChildReport_eyeResults_eyeMovementAndPosition
BeModelChildReport_eyeResults_eyeRemarks "0..1" --> BeModelChildReport_eyeResults
BeModelChildReport_eyeResults_eyeRemarks_subject "1..1" --> BeModelChildReport_eyeResults_eyeRemarks
BeModelChildReport_eyeResults_eyeRemarks_date "1..1" --> BeModelChildReport_eyeResults_eyeRemarks
BeModelChildReport_eyeResults_eyeRemarks_code "1..1" --> BeModelChildReport_eyeResults_eyeRemarks
BeModelChildReport_eyeResults_eyeRemarks_valueString "1..1" --> BeModelChildReport_eyeResults_eyeRemarks
BeModelChildReport_inTreatmentWithOphthalmologist "0..*" --> BeModelChildReport
BeModelChildReport_inTreatmentWithOphthalmologist_date "1..1" --> BeModelChildReport_inTreatmentWithOphthalmologist
BeModelChildReport_inTreatmentWithOphthalmologist_code "1..1" --> BeModelChildReport_inTreatmentWithOphthalmologist
BeModelChildReport_inTreatmentWithOphthalmologist_valueCode "1..1" --> BeModelChildReport_inTreatmentWithOphthalmologist
BeModelDocument <|-- BeModelChildReport
@enduml