@startuml
skinparam shadowing false
skinparam classAttributeIconSize 0
skinparam linetype ortho
skinparam class {
  BackgroundColor #FEFECE
  BorderColor #000000
  ArrowColor #000000
  FontStyle bold
  AttributeFontStyle normal
}
hide circle
hide empty members

class "BeModelPatient" as BeModelPatient <<model>> {
}

class "names" as BeModelPatient_names <<BackboneElement>> {
}

class "usage" as BeModelPatient_names_usage <<CodeableConcept>> {
}

class "familyname" as BeModelPatient_names_familyname <<string>> {
}

class "firstnames" as BeModelPatient_names_firstnames <<string>> {
}

class "title" as BeModelPatient_names_title <<string>> {
}

class "period" as BeModelPatient_names_period <<Period>> {
}

class "birth" as BeModelPatient_birth <<BackboneElement>> {
}

class "address" as BeModelPatient_birth_address <<Address>> {
}

class "date" as BeModelPatient_birth_date <<dateTime>> {
}

class "gender" as BeModelPatient_gender <<BackboneElement>> {
}

class "administrative" as BeModelPatient_gender_administrative <<CodeableConcept>> {
}

class "atbirth" as BeModelPatient_gender_atbirth <<CodeableConcept>> {
}

class "social" as BeModelPatient_gender_social <<CodeableConcept>> {
}

class "nationality" as BeModelPatient_nationality <<CodeableConcept>> {
}

class "residence" as BeModelPatient_residence <<Address>> {
}

class "death" as BeModelPatient_death <<BackboneElement>> {
}

class "date" as BeModelPatient_death_date <<dateTime>> {
}

class "deceased" as BeModelPatient_death_deceased <<boolean>> {
}

class "maritalstatus" as BeModelPatient_maritalstatus <<CodeableConcept>> {
}

BeModelPatient *-- "0..*" BeModelPatient_names
BeModelPatient_names *-- "0..1" BeModelPatient_names_usage
BeModelPatient_names *-- "0..1" BeModelPatient_names_familyname
BeModelPatient_names *-- "0..1" BeModelPatient_names_firstnames
BeModelPatient_names *-- "0..1" BeModelPatient_names_title
BeModelPatient_names *-- "0..1" BeModelPatient_names_period
BeModelPatient *-- "0..1" BeModelPatient_birth
BeModelPatient_birth *-- "0..1" BeModelPatient_birth_address
BeModelPatient_birth *-- "0..1" BeModelPatient_birth_date
BeModelPatient *-- "0..1" BeModelPatient_gender
BeModelPatient_gender *-- "0..1" BeModelPatient_gender_administrative
BeModelPatient_gender *-- "0..1" BeModelPatient_gender_atbirth
BeModelPatient_gender *-- "0..1" BeModelPatient_gender_social
BeModelPatient *-- "0..*" BeModelPatient_nationality
BeModelPatient *-- "0..*" BeModelPatient_residence
BeModelPatient *-- "0..1" BeModelPatient_death
BeModelPatient_death *-- "0..1" BeModelPatient_death_date
BeModelPatient_death *-- "0..1" BeModelPatient_death_deceased
BeModelPatient *-- "0..1" BeModelPatient_maritalstatus
@enduml