@startuml
skinparam ClassBackgroundColor #B5E8F7
skinparam linetype polyline
hide circle
hide stereotype

class "**BeModelPatient**" as BeModelPatient {
|_ names 0..*  
  |_ usage 0..1   <<CodeableConcept>>  
  |_ familyname 0..1   <<string>>  
  |_ firstnames 0..1   <<string>>  
  |_ title 0..1   <<string>>  
  |_ period 0..1   <<Period>>  
|_ birth 0..1  
  |_ address 0..1   <<Address>>  
  |_ date 0..1   <<dateTime>>  
|_ gender 0..1  
  |_ administrative 0..1   <<CodeableConcept>>  
  |_ atbirth 0..1   <<CodeableConcept>>  
  |_ social 0..1   <<CodeableConcept>>  
|_ nationality 0..*   <<CodeableConcept>>  
|_ residence 0..*   <<Address>>  
|_ death 0..1  
  |_ date 0..1   <<dateTime>>  
  |_ deceased 0..1   <<boolean>>  
|_ maritalstatus 0..1   <<CodeableConcept>>  
--
}

@enduml