@startuml
skinparam ClassBackgroundColor #B5E8F7
skinparam linetype polyline
hide circle
hide stereotype

class "**BeModelPopulationScreeningPlan**" as BeModelPopulationScreeningPlan {
|_ patient 1..1   <<Reference(Patient)>>  
|_ screeningType 1..1   <<CodeableConcept>>  
|_ screeningEpisode 0..*   <<BeModelPopulationScreening>>  
--
}

@enduml