@startuml
left to right direction
skinparam shadowing false
skinparam nodesep 10
skinparam ranksep 40
skinparam classAttributeIconSize 0
skinparam class {
  FontStyle italic
  BackgroundColor<<rootconcept>> #FAC08F
  BorderColor<<rootconcept>> #E36C0A
  BackgroundColor<<data>> #B8CCE4
  BorderColor<<data>> #4F81BD
  BackgroundColor<<reference>> #D9D9D9
  BorderColor<<reference>> #808080
  BackgroundColor<<value set>> #C3D69B
  BorderColor<<value set>> #77933C
  ArrowColor #4F81BD
}
hide circle
hide empty members

class "BeModelClinicalReport" as BeModelClinicalReport <<rootconcept>> {
}

class "businessIdentifier" as BeModelClinicalReport_businessIdentifier <<data>> {
}

class "basedOn" as BeModelClinicalReport_basedOn <<reference>> {
}

class "recordedDate" as BeModelClinicalReport_recordedDate <<data>> {
}

class "observationPeriod" as BeModelClinicalReport_observationPeriod <<data>> {
}

class "patient" as BeModelClinicalReport_patient <<reference>> {
}

class "recorder" as BeModelClinicalReport_recorder <<reference>> {
}

class "interpreter" as BeModelClinicalReport_interpreter <<reference>> {
}

class "interpretation" as BeModelClinicalReport_interpretation <<data>> {
}

class "conclusion" as BeModelClinicalReport_conclusion <<data>> {
}

class "category" as BeModelClinicalReport_category <<data>> {
}

class "be-vs-clinicalreport-category" as BeModelClinicalReport_category_vs <<value set>> {
}

class "code" as BeModelClinicalReport_code <<data>> {
}

class "be-vs-clinicalreport-code" as BeModelClinicalReport_code_vs <<value set>> {
}

class "clinicalObservations" as BeModelClinicalReport_clinicalObservations <<reference>> {
}

class "note" as BeModelClinicalReport_note <<data>> {
}

class "document" as BeModelClinicalReport_document <<data>> {
}

class "status" as BeModelClinicalReport_status <<data>> {
}

class "diagnostic-report-status" as BeModelClinicalReport_status_vs <<value set>> {
}

BeModelClinicalReport_category <-- BeModelClinicalReport_category_vs
BeModelClinicalReport_code <-- BeModelClinicalReport_code_vs
BeModelClinicalReport_status <-- BeModelClinicalReport_status_vs
BeModelClinicalReport_businessIdentifier "1..*" --> BeModelClinicalReport
BeModelClinicalReport_basedOn "0..1" --> BeModelClinicalReport
BeModelClinicalReport_recordedDate "1..1" --> BeModelClinicalReport
BeModelClinicalReport_observationPeriod "1..1" --> BeModelClinicalReport
BeModelClinicalReport_patient "1..1" --> BeModelClinicalReport
BeModelClinicalReport_recorder "1..1" --> BeModelClinicalReport
BeModelClinicalReport_interpreter "0..1" --> BeModelClinicalReport
BeModelClinicalReport_interpretation "0..1" --> BeModelClinicalReport
BeModelClinicalReport_conclusion "0..*" --> BeModelClinicalReport
BeModelClinicalReport_category "0..*" --> BeModelClinicalReport
BeModelClinicalReport_code "1..1" --> BeModelClinicalReport
BeModelClinicalReport_clinicalObservations "0..*" --> BeModelClinicalReport
BeModelClinicalReport_note "0..*" --> BeModelClinicalReport
BeModelClinicalReport_document "0..1" --> BeModelClinicalReport
BeModelClinicalReport_status "1..1" --> BeModelClinicalReport
@enduml