@startuml
skinparam ClassBackgroundColor #B5E8F7
skinparam linetype polyline
hide circle
hide stereotype

class "**BeModelBodySite**" as BeModelBodySite {
|_ bodyLocation 0..1   <<CodeableConcept>>  
|_ bodyLaterality 0..1   <<CodeableConcept>>  
|_ bodyTopography 0..1   <<CodeableConcept>>  
--
}

@enduml