@startuml
skinparam shadowing false
skinparam classAttributeIconSize 0
skinparam linetype ortho
skinparam class {
  BackgroundColor #FEFECE
  BorderColor #000000
  ArrowColor #000000
  FontStyle bold
  AttributeFontStyle normal
}
hide circle
hide empty members

class "BeModelEAgreementResponse" as BeModelEAgreementResponse <<model>> {
}

class "patient" as BeModelEAgreementResponse_patient <<Identifier>> {
}

class "rejectionReason" as BeModelEAgreementResponse_rejectionReason <<CodeableConcept>> {
}

class "serviceProvider" as BeModelEAgreementResponse_serviceProvider <<Identifier>> {
}

class "eAgreementType" as BeModelEAgreementResponse_eAgreementType <<CodeableConcept>> {
}

class "decisionId" as BeModelEAgreementResponse_decisionId <<Identifier>> {
}

class "pathologicalSituation" as BeModelEAgreementResponse_pathologicalSituation <<CodeableConcept>> {
}

class "decisionType" as BeModelEAgreementResponse_decisionType <<CodeableConcept>> {
}

class "decisionDate" as BeModelEAgreementResponse_decisionDate <<dateTime>> {
}

class "insurer" as BeModelEAgreementResponse_insurer <<Identifier>> {
}

class "agreementStartDate" as BeModelEAgreementResponse_agreementStartDate <<dateTime>> {
}

class "agreementEndDate" as BeModelEAgreementResponse_agreementEndDate <<dateTime>> {
}

class "refusalReason" as BeModelEAgreementResponse_refusalReason <<CodeableConcept>> {
}

class "additionalInfoReason" as BeModelEAgreementResponse_additionalInfoReason <<CodeableConcept>> {
}

BeModelEAgreementResponse *-- "0..1" BeModelEAgreementResponse_patient
BeModelEAgreementResponse *-- "0..*" BeModelEAgreementResponse_rejectionReason
BeModelEAgreementResponse *-- "0..1" BeModelEAgreementResponse_serviceProvider
BeModelEAgreementResponse *-- "0..1" BeModelEAgreementResponse_eAgreementType
BeModelEAgreementResponse *-- "0..1" BeModelEAgreementResponse_decisionId
BeModelEAgreementResponse *-- "0..1" BeModelEAgreementResponse_pathologicalSituation
BeModelEAgreementResponse *-- "0..1" BeModelEAgreementResponse_decisionType
BeModelEAgreementResponse *-- "0..1" BeModelEAgreementResponse_decisionDate
BeModelEAgreementResponse *-- "0..1" BeModelEAgreementResponse_insurer
BeModelEAgreementResponse *-- "0..1" BeModelEAgreementResponse_agreementStartDate
BeModelEAgreementResponse *-- "0..1" BeModelEAgreementResponse_agreementEndDate
BeModelEAgreementResponse *-- "0..*" BeModelEAgreementResponse_refusalReason
BeModelEAgreementResponse *-- "0..*" BeModelEAgreementResponse_additionalInfoReason
@enduml