@startuml
skinparam shadowing false
skinparam classAttributeIconSize 0
skinparam linetype ortho
skinparam class {
  BackgroundColor #FEFECE
  BorderColor #000000
  ArrowColor #000000
  FontStyle bold
  AttributeFontStyle normal
}
hide circle
hide empty members

class "BeModelMedicationDispense" as BeModelMedicationDispense <<model>> {
}

class "identifier" as BeModelMedicationDispense_identifier <<Identifier>> {
}

class "recordedDate" as BeModelMedicationDispense_recordedDate <<dateTime>> {
}

class "basedOnMedicationLine" as BeModelMedicationDispense_basedOnMedicationLine <<Reference(BeModelMedicationLine)>> {
}

class "patient" as BeModelMedicationDispense_patient <<Reference(be-patient)>> {
}

class "status" as BeModelMedicationDispense_status <<code>> {
  medicationdispense-status
}

class "statusReason" as BeModelMedicationDispense_statusReason <<CodeableConcept>> {
  medicationdispense-status-reason
}

class "dispenser" as BeModelMedicationDispense_dispenser <<BackboneElement>> {
}

class "dispenser" as BeModelMedicationDispense_dispenser_dispenser <<Reference(be-practitioner)>> {
}

class "organization" as BeModelMedicationDispense_dispenser_organization <<Reference(be-organization)>> {
}

class "dispenseDate" as BeModelMedicationDispense_dispenseDate <<dateTime>> {
}

class "prescription" as BeModelMedicationDispense_prescription <<BackboneElement>> {
}

class "isPrescribed" as BeModelMedicationDispense_prescription_isPrescribed <<boolean>> {
}

class "prescription" as BeModelMedicationDispense_prescription_prescription <<Reference>> {
}

class "dispensedItem" as BeModelMedicationDispense_dispensedItem <<BackboneElement>> {
}

class "product" as BeModelMedicationDispense_dispensedItem_product <<CodeableConcept>> {
}

class "quantityDispensed" as BeModelMedicationDispense_dispensedItem_quantityDispensed <<Quantity>> {
}

class "dosage" as BeModelMedicationDispense_dispensedItem_dosage <<Dosage>> {
}

class "offLabel" as BeModelMedicationDispense_dispensedItem_offLabel <<CodeableConcept>> {
}

class "note" as BeModelMedicationDispense_note <<Annotation>> {
}

BeModelMedicationDispense *-- "0..*" BeModelMedicationDispense_identifier
BeModelMedicationDispense *-- "0..1" BeModelMedicationDispense_recordedDate
BeModelMedicationDispense *-- "0..1" BeModelMedicationDispense_basedOnMedicationLine
BeModelMedicationDispense *-- "1..1" BeModelMedicationDispense_patient
BeModelMedicationDispense *-- "1..1" BeModelMedicationDispense_status
BeModelMedicationDispense *-- "0..1" BeModelMedicationDispense_statusReason
BeModelMedicationDispense *-- "0..1" BeModelMedicationDispense_dispenser
BeModelMedicationDispense_dispenser *-- "0..1" BeModelMedicationDispense_dispenser_dispenser
BeModelMedicationDispense_dispenser *-- "0..1" BeModelMedicationDispense_dispenser_organization
BeModelMedicationDispense *-- "1..1" BeModelMedicationDispense_dispenseDate
BeModelMedicationDispense *-- "0..1" BeModelMedicationDispense_prescription
BeModelMedicationDispense_prescription *-- "0..1" BeModelMedicationDispense_prescription_isPrescribed
BeModelMedicationDispense_prescription *-- "0..1" BeModelMedicationDispense_prescription_prescription
BeModelMedicationDispense *-- "1..1" BeModelMedicationDispense_dispensedItem
BeModelMedicationDispense_dispensedItem *-- "1..1" BeModelMedicationDispense_dispensedItem_product
BeModelMedicationDispense_dispensedItem *-- "0..1" BeModelMedicationDispense_dispensedItem_quantityDispensed
BeModelMedicationDispense_dispensedItem *-- "0..*" BeModelMedicationDispense_dispensedItem_dosage
BeModelMedicationDispense_dispensedItem *-- "0..1" BeModelMedicationDispense_dispensedItem_offLabel
BeModelMedicationDispense *-- "0..*" BeModelMedicationDispense_note
@enduml