@startuml
skinparam ClassBackgroundColor #B5E8F7
skinparam linetype polyline
hide circle
hide stereotype

class "**MedicationLine**" as MedicationLine {
|_ identifier 1..*   <<Identifier>>  
|_ recordedDate 1..1   <<dateTime>>  
|_ recorder 1..1   <<Reference(be-practitioner)>>  
|_ patient 1..1   <<Reference(be-patient)>>  
|_ status 1..1   <<code>>  
|_ adherence 0..1  
  |_ status 1..1   <<CodeableConcept>>  
  |_ adherenceStatusReason 0..1   <<CodeableConcept>>  
|_ medication 1..1  
  |_ product 1..1   <<Reference(BeModelMedication)>>  
  |_ type 1..1   <<CodeableConcept>>  
|_ reason 0..*  
  |_ reference 0..1   <<Reference>>  
  |_ code 0..1   <<CodeableConcept>>  
|_ effectivePeriod 1..1  
  |_ start 1..1   <<dateTime>>  
  |_ end 0..1   <<dateTime>>  
|_ dosage 0..*   <<BeModelDosagingInformation>>  
|_ offLabel 0..1   <<string>>  
|_ exposure 0..1   <<CodeableConcept>>  
|_ originType 0..1   <<CodeableConcept>>  
|_ note 0..*   <<Annotation>>  
--
}

@enduml