@startuml
skinparam shadowing false
skinparam classAttributeIconSize 0
skinparam linetype ortho
skinparam class {
  BackgroundColor #FEFECE
  BorderColor #000000
  ArrowColor #000000
  FontStyle bold
  AttributeFontStyle normal
}
hide circle
hide empty members

class "MedicationLine" as MedicationLine <<model>> {
}

class "identifier" as MedicationLine_identifier <<Identifier>> {
}

class "recordedDate" as MedicationLine_recordedDate <<dateTime>> {
}

class "recorder" as MedicationLine_recorder <<Reference(be-practitioner)>> {
}

class "patient" as MedicationLine_patient <<Reference(be-patient)>> {
}

class "status" as MedicationLine_status <<code>> {
}

class "adherence" as MedicationLine_adherence <<BackboneElement>> {
}

class "status" as MedicationLine_adherence_status <<CodeableConcept>> {
  BeMedicationLineAdherenceStatusVS
}

class "adherenceStatusReason" as MedicationLine_adherence_adherenceStatusReason <<CodeableConcept>> {
  BeMedicationLineAdherenceStatusReasonVS
}

class "medication" as MedicationLine_medication <<BackboneElement>> {
}

class "product" as MedicationLine_medication_product <<Reference(BeModelMedication)>> {
}

class "type" as MedicationLine_medication_type <<CodeableConcept>> {
  BeMedicationTypeVS
}

class "reason" as MedicationLine_reason <<BackboneElement>> {
}

class "reference" as MedicationLine_reason_reference <<Reference>> {
}

class "code" as MedicationLine_reason_code <<CodeableConcept>> {
}

class "effectivePeriod" as MedicationLine_effectivePeriod <<BackboneElement>> {
}

class "start" as MedicationLine_effectivePeriod_start <<dateTime>> {
}

class "end" as MedicationLine_effectivePeriod_end <<dateTime>> {
}

class "dosage" as MedicationLine_dosage <<BeModelDosagingInformation>> {
}

class "offLabel" as MedicationLine_offLabel <<string>> {
}

class "exposure" as MedicationLine_exposure <<CodeableConcept>> {
  BeMedicationExposureIntentVS
}

class "originType" as MedicationLine_originType <<CodeableConcept>> {
  BeMedicationLineOriginTypeVS
}

class "note" as MedicationLine_note <<Annotation>> {
}

MedicationLine *-- "1..*" MedicationLine_identifier
MedicationLine *-- "1..1" MedicationLine_recordedDate
MedicationLine *-- "1..1" MedicationLine_recorder
MedicationLine *-- "1..1" MedicationLine_patient
MedicationLine *-- "1..1" MedicationLine_status
MedicationLine *-- "0..1" MedicationLine_adherence
MedicationLine_adherence *-- "1..1" MedicationLine_adherence_status
MedicationLine_adherence *-- "0..1" MedicationLine_adherence_adherenceStatusReason
MedicationLine *-- "1..1" MedicationLine_medication
MedicationLine_medication *-- "1..1" MedicationLine_medication_product
MedicationLine_medication *-- "1..1" MedicationLine_medication_type
MedicationLine *-- "0..*" MedicationLine_reason
MedicationLine_reason *-- "0..1" MedicationLine_reason_reference
MedicationLine_reason *-- "0..1" MedicationLine_reason_code
MedicationLine *-- "1..1" MedicationLine_effectivePeriod
MedicationLine_effectivePeriod *-- "1..1" MedicationLine_effectivePeriod_start
MedicationLine_effectivePeriod *-- "0..1" MedicationLine_effectivePeriod_end
MedicationLine *-- "0..*" MedicationLine_dosage
MedicationLine *-- "0..1" MedicationLine_offLabel
MedicationLine *-- "0..1" MedicationLine_exposure
MedicationLine *-- "0..1" MedicationLine_originType
MedicationLine *-- "0..*" MedicationLine_note
@enduml