@startuml
skinparam shadowing false
skinparam classAttributeIconSize 0
skinparam linetype ortho
skinparam class {
  BackgroundColor #FEFECE
  BorderColor #000000
  ArrowColor #000000
  FontStyle bold
  AttributeFontStyle normal
}
hide circle
hide empty members

class "PregnancyStatusDataSet" as PregnancyStatusDataSet <<model>> {
}

class "pregnancy" as PregnancyStatusDataSet_pregnancy <<Base>> {
}

class "patient" as PregnancyStatusDataSet_pregnancy_patient <<Reference(Patient)>> {
}

class "author" as PregnancyStatusDataSet_pregnancy_author <<Reference(Practitioner)>> {
}

class "updateDate" as PregnancyStatusDataSet_pregnancy_updateDate <<date>> {
}

class "firstRecordedDate" as PregnancyStatusDataSet_pregnancy_firstRecordedDate <<date>> {
}

class "pregnancyStatus" as PregnancyStatusDataSet_pregnancy_pregnancyStatus <<Base>> {
}

class "value" as PregnancyStatusDataSet_pregnancy_pregnancyStatus_value <<CodeableConcept>> {
}

class "author" as PregnancyStatusDataSet_pregnancy_pregnancyStatus_author <<Reference(Practitioner)>> {
}

class "pregnancyStartDate" as PregnancyStatusDataSet_pregnancy_pregnancyStatus_pregnancyStartDate <<Base>> {
}

class "value" as PregnancyStatusDataSet_pregnancy_pregnancyStatus_pregnancyStartDate_value <<date>> {
}

class "estimatedDateOfDelivery" as PregnancyStatusDataSet_pregnancy_pregnancyStatus_estimatedDateOfDelivery <<Base>> {
}

class "value" as PregnancyStatusDataSet_pregnancy_pregnancyStatus_estimatedDateOfDelivery_value <<date>> {
}

class "dateOfEndOfPregnancy" as PregnancyStatusDataSet_pregnancy_pregnancyStatus_dateOfEndOfPregnancy <<Base>> {
}

class "value" as PregnancyStatusDataSet_pregnancy_pregnancyStatus_dateOfEndOfPregnancy_value <<date>> {
}

class "expectedNumberOfChildren" as PregnancyStatusDataSet_pregnancy_pregnancyStatus_expectedNumberOfChildren <<Base>> {
}

class "value" as PregnancyStatusDataSet_pregnancy_pregnancyStatus_expectedNumberOfChildren_value <<integer>> {
}

PregnancyStatusDataSet *-- "1..1" PregnancyStatusDataSet_pregnancy
PregnancyStatusDataSet_pregnancy *-- "1..1" PregnancyStatusDataSet_pregnancy_patient
PregnancyStatusDataSet_pregnancy *-- "1..1" PregnancyStatusDataSet_pregnancy_author
PregnancyStatusDataSet_pregnancy *-- "1..1" PregnancyStatusDataSet_pregnancy_updateDate
PregnancyStatusDataSet_pregnancy *-- "1..1" PregnancyStatusDataSet_pregnancy_firstRecordedDate
PregnancyStatusDataSet_pregnancy *-- "1..1" PregnancyStatusDataSet_pregnancy_pregnancyStatus
PregnancyStatusDataSet_pregnancy_pregnancyStatus *-- "1..1" PregnancyStatusDataSet_pregnancy_pregnancyStatus_value
PregnancyStatusDataSet_pregnancy_pregnancyStatus *-- "1..1" PregnancyStatusDataSet_pregnancy_pregnancyStatus_author
PregnancyStatusDataSet_pregnancy_pregnancyStatus *-- "1..1" PregnancyStatusDataSet_pregnancy_pregnancyStatus_pregnancyStartDate
PregnancyStatusDataSet_pregnancy_pregnancyStatus_pregnancyStartDate *-- "1..1" PregnancyStatusDataSet_pregnancy_pregnancyStatus_pregnancyStartDate_value
PregnancyStatusDataSet_pregnancy_pregnancyStatus *-- "1..1" PregnancyStatusDataSet_pregnancy_pregnancyStatus_estimatedDateOfDelivery
PregnancyStatusDataSet_pregnancy_pregnancyStatus_estimatedDateOfDelivery *-- "1..1" PregnancyStatusDataSet_pregnancy_pregnancyStatus_estimatedDateOfDelivery_value
PregnancyStatusDataSet_pregnancy_pregnancyStatus *-- "0..1" PregnancyStatusDataSet_pregnancy_pregnancyStatus_dateOfEndOfPregnancy
PregnancyStatusDataSet_pregnancy_pregnancyStatus_dateOfEndOfPregnancy *-- "1..1" PregnancyStatusDataSet_pregnancy_pregnancyStatus_dateOfEndOfPregnancy_value
PregnancyStatusDataSet_pregnancy_pregnancyStatus *-- "1..1" PregnancyStatusDataSet_pregnancy_pregnancyStatus_expectedNumberOfChildren
PregnancyStatusDataSet_pregnancy_pregnancyStatus_expectedNumberOfChildren *-- "1..1" PregnancyStatusDataSet_pregnancy_pregnancyStatus_expectedNumberOfChildren_value
@enduml