@startuml
skinparam ClassBackgroundColor #B5E8F7
skinparam linetype polyline
hide circle
hide stereotype

class "**PregnancyStatusDataSet**" as PregnancyStatusDataSet {
|_ pregnancy 1..1  
  |_ patient 1..1   <<Reference(Patient)>>  
  |_ author 1..1   <<Reference(Practitioner)>>  
  |_ updateDate 1..1   <<date>>  
  |_ firstRecordedDate 1..1   <<date>>  
  |_ pregnancyStatus 1..1  
    |_ value 1..1   <<CodeableConcept>>  
    |_ author 1..1   <<Reference(Practitioner)>>  
    |_ pregnancyStartDate 1..1  
      |_ value 1..1   <<date>>  
    |_ estimatedDateOfDelivery 1..1  
      |_ value 1..1   <<date>>  
    |_ dateOfEndOfPregnancy 0..1  
      |_ value 1..1   <<date>>  
    |_ expectedNumberOfChildren 1..1  
      |_ value 1..1   <<integer>>  
--
}

@enduml