@startuml
left to right direction
skinparam shadowing false
skinparam nodesep 10
skinparam ranksep 40
skinparam classAttributeIconSize 0
skinparam class {
  FontStyle italic
  BackgroundColor<<rootconcept>> #FAC08F
  BorderColor<<rootconcept>> #E36C0A
  BackgroundColor<<data>> #B8CCE4
  BorderColor<<data>> #4F81BD
  BackgroundColor<<reference>> #D9D9D9
  BorderColor<<reference>> #808080
  BackgroundColor<<value set>> #C3D69B
  BorderColor<<value set>> #77933C
  ArrowColor #4F81BD
}
hide circle
hide empty members

class "PSSConsentModel" as PSSConsentModel <<rootconcept>> {
}

class "hcpID" as PSSConsentModel_hcpID <<data>> {
}

class "recordedDate" as PSSConsentModel_recordedDate <<data>> {
}

class "instruction" as PSSConsentModel_instruction <<data>> {
}

class "termsConditions" as PSSConsentModel_termsConditions <<rootconcept>> {
}

class "policy" as PSSConsentModel_termsConditions_policy <<data>> {
}

class "version" as PSSConsentModel_termsConditions_version <<data>> {
}

class "consent" as PSSConsentModel_consent <<data>> {
}

class "provision" as PSSConsentModel_provision <<rootconcept>> {
}

class "provisionType" as PSSConsentModel_provision_provisionType <<data>> {
}

class "provisionStatus" as PSSConsentModel_provision_provisionStatus <<data>> {
}

PSSConsentModel_hcpID "1..1" --> PSSConsentModel
PSSConsentModel_recordedDate "1..1" --> PSSConsentModel
PSSConsentModel_instruction "1..1" --> PSSConsentModel
PSSConsentModel_termsConditions "1..1" --> PSSConsentModel
PSSConsentModel_termsConditions_policy "1..1" --> PSSConsentModel_termsConditions
PSSConsentModel_termsConditions_version "1..1" --> PSSConsentModel_termsConditions
PSSConsentModel_consent "1..1" --> PSSConsentModel
PSSConsentModel_provision "0..1" --> PSSConsentModel
PSSConsentModel_provision_provisionType "1..1" --> PSSConsentModel_provision
PSSConsentModel_provision_provisionStatus "1..1" --> PSSConsentModel_provision
@enduml