@startuml
skinparam shadowing false
skinparam classAttributeIconSize 0
skinparam linetype ortho
skinparam class {
  BackgroundColor #FEFECE
  BorderColor #000000
  ArrowColor #000000
  FontStyle bold
  AttributeFontStyle normal
}
hide circle
hide empty members

class "PSSConsentModel" as PSSConsentModel <<model>> {
}

class "hcpID" as PSSConsentModel_hcpID <<string>> {
}

class "recordedDate" as PSSConsentModel_recordedDate <<date>> {
}

class "instruction" as PSSConsentModel_instruction <<string>> {
}

class "termsConditions" as PSSConsentModel_termsConditions <<BackboneElement>> {
}

class "policy" as PSSConsentModel_termsConditions_policy <<uri>> {
}

class "version" as PSSConsentModel_termsConditions_version <<string>> {
}

class "consent" as PSSConsentModel_consent <<code>> {
}

class "provision" as PSSConsentModel_provision <<BackboneElement>> {
}

class "provisionType" as PSSConsentModel_provision_provisionType <<code>> {
}

class "provisionStatus" as PSSConsentModel_provision_provisionStatus <<code>> {
}

PSSConsentModel *-- "1..1" PSSConsentModel_hcpID
PSSConsentModel *-- "1..1" PSSConsentModel_recordedDate
PSSConsentModel *-- "1..1" PSSConsentModel_instruction
PSSConsentModel *-- "1..1" PSSConsentModel_termsConditions
PSSConsentModel_termsConditions *-- "1..1" PSSConsentModel_termsConditions_policy
PSSConsentModel_termsConditions *-- "1..1" PSSConsentModel_termsConditions_version
PSSConsentModel *-- "1..1" PSSConsentModel_consent
PSSConsentModel *-- "0..1" PSSConsentModel_provision
PSSConsentModel_provision *-- "1..1" PSSConsentModel_provision_provisionType
PSSConsentModel_provision *-- "1..1" PSSConsentModel_provision_provisionStatus
@enduml