@startuml
skinparam shadowing false
skinparam classAttributeIconSize 0
skinparam linetype ortho
skinparam class {
  BackgroundColor #FEFECE
  BorderColor #000000
  ArrowColor #000000
  FontStyle bold
  AttributeFontStyle normal
}
hide circle
hide empty members

class "PSSResponse" as PSSResponse <<model>> {
}

class "recordedDate" as PSSResponse_recordedDate <<date>> {
}

class "pssID" as PSSResponse_pssID <<Identifier>> {
}

class "indication" as PSSResponse_indication <<CodeableConcept>> {
}

class "status" as PSSResponse_status <<CodeableConcept>> {
}

class "treatmentOptions" as PSSResponse_treatmentOptions <<BackboneElement>> {
}

class "identifier" as PSSResponse_treatmentOptions_identifier <<Identifier>> {
}

class "instruction" as PSSResponse_treatmentOptions_instruction <<CodeableConcept>> {
}

class "scoreRating" as PSSResponse_treatmentOptions_scoreRating <<CodeableConcept>> {
}

class "radiationExposure" as PSSResponse_treatmentOptions_radiationExposure <<Quantity>> {
}

class "evidenceSource" as PSSResponse_evidenceSource <<Reference(ResearchStudy)>> {
}

PSSResponse *-- "1..1" PSSResponse_recordedDate
PSSResponse *-- "1..1" PSSResponse_pssID
PSSResponse *-- "1..1" PSSResponse_indication
PSSResponse *-- "1..1" PSSResponse_status
PSSResponse *-- "1..*" PSSResponse_treatmentOptions
PSSResponse_treatmentOptions *-- "1..1" PSSResponse_treatmentOptions_identifier
PSSResponse_treatmentOptions *-- "1..1" PSSResponse_treatmentOptions_instruction
PSSResponse_treatmentOptions *-- "1..1" PSSResponse_treatmentOptions_scoreRating
PSSResponse_treatmentOptions *-- "1..1" PSSResponse_treatmentOptions_radiationExposure
PSSResponse *-- "1..1" PSSResponse_evidenceSource
@enduml