@startuml
left to right direction
skinparam shadowing false
skinparam nodesep 10
skinparam ranksep 40
skinparam classAttributeIconSize 0
skinparam class {
  FontStyle italic
  BackgroundColor<<rootconcept>> #FAC08F
  BorderColor<<rootconcept>> #E36C0A
  BackgroundColor<<data>> #B8CCE4
  BorderColor<<data>> #4F81BD
  BackgroundColor<<reference>> #D9D9D9
  BorderColor<<reference>> #808080
  BackgroundColor<<value set>> #C3D69B
  BorderColor<<value set>> #77933C
  ArrowColor #4F81BD
}
hide circle
hide empty members

class "PSSRequest" as PSSRequest <<rootconcept>> {
}

class "recordedDate" as PSSRequest_recordedDate <<data>> {
}

class "pssID" as PSSRequest_pssID <<data>> {
}

class "examination" as PSSRequest_examination <<reference>> {
}

class "indication" as PSSRequest_indication <<data>> {
}

class "supportingInfo" as PSSRequest_supportingInfo <<rootconcept>> {
}

class "patientAge" as PSSRequest_supportingInfo_patientAge <<data>> {
}

class "patientGender" as PSSRequest_supportingInfo_patientGender <<data>> {
}

PSSRequest_recordedDate "1..1" --> PSSRequest
PSSRequest_pssID "1..1" --> PSSRequest
PSSRequest_examination "0..1" --> PSSRequest
PSSRequest_indication "1..*" --> PSSRequest
PSSRequest_supportingInfo "1..1" --> PSSRequest
PSSRequest_supportingInfo_patientAge "1..1" --> PSSRequest_supportingInfo
PSSRequest_supportingInfo_patientGender "1..1" --> PSSRequest_supportingInfo
@enduml