@startuml
skinparam shadowing false
skinparam classAttributeIconSize 0
skinparam linetype ortho
skinparam class {
  BackgroundColor #FEFECE
  BorderColor #000000
  ArrowColor #000000
  FontStyle bold
  AttributeFontStyle normal
}
hide circle
hide empty members

class "PSSRequest" as PSSRequest <<model>> {
}

class "recordedDate" as PSSRequest_recordedDate <<date>> {
}

class "pssID" as PSSRequest_pssID <<Identifier>> {
}

class "examination" as PSSRequest_examination <<Reference>> {
}

class "indication" as PSSRequest_indication <<CodeableConcept>> {
}

class "supportingInfo" as PSSRequest_supportingInfo <<BackboneElement>> {
}

class "patientAge" as PSSRequest_supportingInfo_patientAge <<Age>> {
}

class "patientGender" as PSSRequest_supportingInfo_patientGender <<CodeableConcept>> {
}

PSSRequest *-- "1..1" PSSRequest_recordedDate
PSSRequest *-- "1..1" PSSRequest_pssID
PSSRequest *-- "0..1" PSSRequest_examination
PSSRequest *-- "1..*" PSSRequest_indication
PSSRequest *-- "1..1" PSSRequest_supportingInfo
PSSRequest_supportingInfo *-- "1..1" PSSRequest_supportingInfo_patientAge
PSSRequest_supportingInfo *-- "1..1" PSSRequest_supportingInfo_patientGender
@enduml