// Generated by make_conceptmap_fsh.py - do not edit by hand.
// Source: input/glossary_mappings.csv (confirmed rows only).
// Regenerate rather than patching: the display page beside this
// file is generated from the same rows and must agree with it.

Instance: PatientwillModelToGlossary
InstanceOf: ConceptMap
Usage: #definition
* url = "http://example.org/ConceptMap/PatientwillModelToGlossary"
* name = "PatientwillModelToGlossary"
* title = "patientwill logical model elements to Common Glossary concepts"
* status = #active
* experimental = false
* date = "2026-09-07"
* copyright = "Published for review. This mapping is provided for information. It carries no conformance requirement and does not modify the logical models, which are published as released. It has not yet completed the CareSets governance review; its coverage is not exhaustive and individual mappings may be revised. Implementations should not depend on it in its present version."
* description = "Maps elements of the patientwill logical models to the concepts of the Belgian Common Glossary. Published as a ConceptMap so the StructureDefinitions remain exactly as released and a change of mapping is not a change of model."

* group[+]
  * source = "https://www.ehealth.fgov.be/standards/fhir/patientwill/StructureDefinition/BeModelPatientWill"
  * target = "http://example.org/CodeSystem/BeSafeShareGlossary"
  * element[+]
    * code = #BeModelPatientWill.category
    * display = "Type of patient wishes."
    * target[+]
      * code = #Category
      * display = "Category"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelPatientWill.identifier
    * display = "Unique identifier"
    * target[+]
      * code = #BusinessIdentifier
      * display = "BusinessIdentifier"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelPatientWill.note
    * display = "Comments"
    * target[+]
      * code = #Note
      * display = "Note"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelPatientWill.patient
    * display = "Is the patient's unique identifier. The unique identifier must be the patient's national patient registry number (NISS) or BIS number."
    * target[+]
      * code = #Patient
      * display = "Patient"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelPatientWill.recordedDate
    * display = "Date of encoding of the information"
    * target[+]
      * code = #RecordedDate
      * display = "RecordedDate"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelPatientWill.recorder
    * display = "Is the unique identifier of either the healthcare professional responsible for the encrypted content, or the patient encoding his or her own wishes, or a representative of the patient encoding the patient's wishes. The unique identifier must be the National Register Number (NISS) or BIS number."
    * target[+]
      * code = #Recorder
      * display = "Recorder"
      * equivalence = #equivalent
