// Generated by make_conceptmap_fsh.py - do not edit by hand.
// Source: input/glossary_mappings.csv (confirmed rows only).
// Regenerate rather than patching: the display page beside this
// file is generated from the same rows and must agree with it.

Instance: AllergyModelToGlossary
InstanceOf: ConceptMap
Usage: #definition
* url = "http://example.org/ConceptMap/AllergyModelToGlossary"
* name = "AllergyModelToGlossary"
* title = "allergy logical model elements to Common Glossary concepts"
* status = #active
* experimental = false
* date = "2026-09-07"
* copyright = "Published for information. This mapping carries no conformance requirement and does not modify the logical models, which are published as released. It remains subject to review: coverage will be extended and individual mappings may be revised in subsequent versions."
* description = "Maps elements of the allergy logical models to the concepts of the Belgian Common Glossary. Published as a ConceptMap so the StructureDefinitions remain exactly as released and a change of mapping is not a change of model."

* group[+]
  * source = "https://www.ehealth.fgov.be/standards/fhir/allergy/StructureDefinition/be-model-allergyintolerance"
  * target = "http://example.org/CodeSystem/BeSafeShareGlossary"
  * element[+]
    * code = #be-model-allergyintolerance.asserter
    * display = "Who asserted the allergy"
    * target[+]
      * code = #Asserter
      * display = "Asserter"
      * equivalence = #equivalent
  * element[+]
    * code = #be-model-allergyintolerance.category
    * display = "The category of the risk (food, medication, environment, biological,...). This information will not be encoded by the Recorder but can automatically be added using the SNOMED-CT code from causative agent"
    * target[+]
      * code = #Category
      * display = "Category"
      * equivalence = #equivalent
  * element[+]
    * code = #be-model-allergyintolerance.code
    * display = "The substance that the person is allergic to"
    * target[+]
      * code = #Code
      * display = "Code"
      * equivalence = #equivalent
  * element[+]
    * code = #be-model-allergyintolerance.note
    * display = "Additional text note about the allergy or intolerance"
    * target[+]
      * code = #Note
      * display = "Note"
      * equivalence = #equivalent
  * element[+]
    * code = #be-model-allergyintolerance.patient
    * display = "The person that has the allergy"
    * target[+]
      * code = #Patient
      * display = "Patient"
      * equivalence = #equivalent
  * element[+]
    * code = #be-model-allergyintolerance.reactions.note
    * display = "Additional text note about the allergic reaction"
    * target[+]
      * code = #Note
      * display = "Note"
      * equivalence = #equivalent
  * element[+]
    * code = #be-model-allergyintolerance.recordedDate
    * display = "when the allergy/intolerance was recorded"
    * target[+]
      * code = #RecordedDate
      * display = "RecordedDate"
      * equivalence = #equivalent
  * element[+]
    * code = #be-model-allergyintolerance.recorder
    * display = "Who recorded the allergy"
    * target[+]
      * code = #Recorder
      * display = "Recorder"
      * equivalence = #equivalent
  * element[+]
    * code = #be-model-allergyintolerance.status
    * display = "The status of the allergy"
    * target[+]
      * code = #Status
      * display = "Status"
      * equivalence = #equivalent
  * element[+]
    * code = #be-model-allergyintolerance.status.clinicalStatus
    * display = "The status of the allergy - if it is active or resolved"
    * target[+]
      * code = #ClinicalStatus
      * display = "ClinicalStatus"
      * equivalence = #equivalent
  * element[+]
    * code = #be-model-allergyintolerance.status.verificationStatus
    * display = "The verification status of the allergy - if it is confirmed or suspected or refuted"
    * target[+]
      * code = #VerificationStatus
      * display = "VerificationStatus"
      * equivalence = #equivalent
