// Generated by make_conceptmap_fsh.py - do not edit by hand.
// Source: input/glossary_mappings.csv (confirmed rows only).
// Regenerate rather than patching: the display page beside this
// file is generated from the same rows and must agree with it.

Instance: CoreModelToGlossary
InstanceOf: ConceptMap
Usage: #definition
* url = "http://example.org/ConceptMap/CoreModelToGlossary"
* name = "CoreModelToGlossary"
* title = "core logical model elements to Common Glossary concepts"
* status = #draft
* experimental = true
* date = "2026-09-07"
* copyright = "Draft release - issued for review. These mappings have not yet been ratified by the CareSets governance process, which is being established alongside this release. They are informative, not normative: they impose no conformance requirement and do not alter the logical models, which are published exactly as released. Coverage is partial and the relationships are indicative, so implementations should not yet rely on them."
* description = "Maps elements of the core logical models to the concepts of the Belgian Common Glossary. Published as a ConceptMap so the StructureDefinitions remain exactly as released and a change of mapping is not a change of model."

* group[+]
  * source = "https://www.ehealth.fgov.be/standards/fhir/core/StructureDefinition/BeModelPatientDocument"
  * target = "http://example.org/CodeSystem/BeSafeShareGlossary"
  * element[+]
    * code = #BeModelPatientDocument.author
    * display = "The author of the document, either Practitioner or Organization"
    * target[+]
      * code = #Recorder
      * display = "Recorder"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelPatientDocument.category
    * display = "A number of classifiers for the document, each code refines the previous one"
    * target[+]
      * code = #Category
      * display = "Category"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelPatientDocument.patient
    * display = "The subject of the document"
    * target[+]
      * code = #Patient
      * display = "Patient"
      * equivalence = #equivalent
