// Generated by make_conceptmap_fsh.py - do not edit by hand.
// Source: input/glossary_mappings.csv (confirmed rows only).
// Regenerate rather than patching: the display page beside this
// file is generated from the same rows and must agree with it.

Instance: MycarenetModelToGlossary
InstanceOf: ConceptMap
Usage: #definition
* extension[+].url = "http://hl7.org/fhir/StructureDefinition/structuredefinition-fmm"
* extension[=].valueInteger = 1
* url = "http://example.org/ConceptMap/MycarenetModelToGlossary"
* name = "MycarenetModelToGlossary"
* version = "0.9.0"
* title = "mycarenet logical model elements to Common Glossary concepts"
* status = #active
* experimental = false
* date = "2026-09-07"
* copyright = "First public release - agreed by the editors and open for review. The mapping is informative: the logical models are published as released and are unchanged by it. Coverage will be extended and individual mappings may be revised as review progresses."
* description = "Maps elements of the mycarenet logical models to the concepts of the Belgian Common Glossary. Published as a ConceptMap so the StructureDefinitions remain exactly as released and a change of mapping is not a change of model."

* group[+]
  * source = "https://www.ehealth.fgov.be/standards/fhir/mycarenet/StructureDefinition/be-model-eagreement"
  * target = "http://example.org/CodeSystem/BeSafeShareGlossary"
  * element[+]
    * code = #be-model-eagreement.patient
    * display = "Patient identification"
    * target[+]
      * code = #Patient
      * display = "Patient"
      * equivalence = #equivalent

* group[+]
  * source = "https://www.ehealth.fgov.be/standards/fhir/mycarenet/StructureDefinition/be-model-eagreement-response"
  * target = "http://example.org/CodeSystem/BeSafeShareGlossary"
  * element[+]
    * code = #be-model-eagreement-response.patient
    * display = "Patient identification"
    * target[+]
      * code = #Patient
      * display = "Patient"
      * equivalence = #equivalent
