// Generated by make_conceptmap_fsh.py - do not edit by hand.
// Source: input/glossary_mappings.csv (confirmed rows only).
// Regenerate rather than patching: the display page beside this
// file is generated from the same rows and must agree with it.

Instance: VaccinationModelToGlossary
InstanceOf: ConceptMap
Usage: #definition
* url = "http://example.org/ConceptMap/VaccinationModelToGlossary"
* name = "VaccinationModelToGlossary"
* title = "vaccination logical model elements to Common Glossary concepts"
* status = #active
* experimental = false
* date = "2026-09-07"
* copyright = "Published for review. This mapping is provided for information. It carries no conformance requirement and does not modify the logical models, which are published as released. It has not yet completed the CareSets governance review; its coverage is not exhaustive and individual mappings may be revised. Implementations should not depend on it in its present version."
* description = "Maps elements of the vaccination logical models to the concepts of the Belgian Common Glossary. Published as a ConceptMap so the StructureDefinitions remain exactly as released and a change of mapping is not a change of model."

* group[+]
  * source = "https://www.ehealth.fgov.be/standards/fhir/vaccination/StructureDefinition/be-model-vaccination"
  * target = "http://example.org/CodeSystem/BeSafeShareGlossary"
  * element[+]
    * code = #be-model-vaccination.administeredProduct.lotNumber
    * display = "The lot number"
    * target[+]
      * code = #LotNumber
      * display = "LotNumber"
      * equivalence = #equivalent
  * element[+]
    * code = #be-model-vaccination.bodyLaterality
    * display = "The side of the body (for sites that occur on both sides of the body)"
    * target[+]
      * code = #BodyLaterality
      * display = "BodyLaterality"
      * equivalence = #equivalent
  * element[+]
    * code = #be-model-vaccination.identifier
    * display = "The business identifier(s) for the vaccination entry"
    * target[+]
      * code = #BusinessIdentifier
      * display = "BusinessIdentifier"
      * equivalence = #equivalent
  * element[+]
    * code = #be-model-vaccination.note
    * display = "Additional notes for the vaccination."
    * target[+]
      * code = #Note
      * display = "Note"
      * equivalence = #equivalent
  * element[+]
    * code = #be-model-vaccination.patient
    * display = "The patient that received vaccination."
    * target[+]
      * code = #Patient
      * display = "Patient"
      * equivalence = #equivalent
  * element[+]
    * code = #be-model-vaccination.performer
    * display = "The professional that administered the medication"
    * target[+]
      * code = #Performer
      * display = "Performer"
      * equivalence = #equivalent
  * element[+]
    * code = #be-model-vaccination.recorded
    * display = "The date and time when the administration of the vaccine was recorded"
    * target[+]
      * code = #RecordedDate
      * display = "RecordedDate"
      * equivalence = #equivalent
  * element[+]
    * code = #be-model-vaccination.recorder
    * display = "The professional that recorded the administration of the vaccine"
    * target[+]
      * code = #Recorder
      * display = "Recorder"
      * equivalence = #equivalent
  * element[+]
    * code = #be-model-vaccination.route
    * display = "The route of administration."
    * target[+]
      * code = #RouteOfAdministration
      * display = "RouteOfAdministration"
      * equivalence = #equivalent
  * element[+]
    * code = #be-model-vaccination.site
    * display = "The body site where the vaccination entered the body"
    * target[+]
      * code = #BodyLocation
      * display = "BodyLocation"
      * equivalence = #equivalent
  * element[+]
    * code = #be-model-vaccination.status
    * display = "The status of this vaccination record entry"
    * target[+]
      * code = #Status
      * display = "Status"
      * equivalence = #equivalent
  * element[+]
    * code = #be-model-vaccination.vaccinationDate[x]
    * display = "The date and time when the vaccination has been administered"
    * target[+]
      * code = #AdministrationDate
      * display = "AdministrationDate"
      * equivalence = #equivalent

* group[+]
  * source = "https://www.ehealth.fgov.be/standards/fhir/vaccination/StructureDefinition/be-model-vaccination-reduced"
  * target = "http://example.org/CodeSystem/BeSafeShareGlossary"
  * element[+]
    * code = #be-model-vaccination-reduced.administeredProduct.lotNumber
    * display = "The lot number"
    * target[+]
      * code = #LotNumber
      * display = "LotNumber"
      * equivalence = #equivalent
  * element[+]
    * code = #be-model-vaccination-reduced.identifier
    * display = "The business identifier(s) for the vaccination entry"
    * target[+]
      * code = #BusinessIdentifier
      * display = "BusinessIdentifier"
      * equivalence = #equivalent
  * element[+]
    * code = #be-model-vaccination-reduced.patient
    * display = "The patient that received vaccination."
    * target[+]
      * code = #Patient
      * display = "Patient"
      * equivalence = #equivalent
  * element[+]
    * code = #be-model-vaccination-reduced.performer
    * display = "The professional that administered the medication"
    * target[+]
      * code = #Performer
      * display = "Performer"
      * equivalence = #equivalent
  * element[+]
    * code = #be-model-vaccination-reduced.recorded
    * display = "The date and time when the administration of the vaccine was recorded"
    * target[+]
      * code = #RecordedDate
      * display = "RecordedDate"
      * equivalence = #equivalent
