// Generated by make_conceptmap_fsh.py - do not edit by hand.
// Source: input/glossary_mappings.csv (confirmed rows only).
// Regenerate rather than patching: the display page beside this
// file is generated from the same rows and must agree with it.

Instance: PublicHealthModelToGlossary
InstanceOf: ConceptMap
Usage: #definition
* url = "http://example.org/ConceptMap/PublicHealthModelToGlossary"
* name = "PublicHealthModelToGlossary"
* title = "public-health logical model elements to Common Glossary concepts"
* status = #active
* experimental = false
* date = "2026-09-07"
* copyright = "Published for review. This mapping is provided for information. It carries no conformance requirement and does not modify the logical models, which are published as released. It has not yet completed the CareSets governance review; its coverage is not exhaustive and individual mappings may be revised. Implementations should not depend on it in its present version."
* description = "Maps elements of the public-health logical models to the concepts of the Belgian Common Glossary. Published as a ConceptMap so the StructureDefinitions remain exactly as released and a change of mapping is not a change of model."

* group[+]
  * source = "https://www.ehealth.fgov.be/standards/fhir/public-health/StructureDefinition/BeModelPopulationScreening"
  * target = "http://example.org/CodeSystem/BeSafeShareGlossary"
  * element[+]
    * code = #BeModelPopulationScreening.patient
    * display = "The patient for the screening"
    * target[+]
      * code = #Patient
      * display = "Patient"
      * equivalence = #equivalent

* group[+]
  * source = "https://www.ehealth.fgov.be/standards/fhir/public-health/StructureDefinition/BeModelPopulationScreeningPlan"
  * target = "http://example.org/CodeSystem/BeSafeShareGlossary"
  * element[+]
    * code = #BeModelPopulationScreeningPlan.patient
    * display = "The patient for the screening"
    * target[+]
      * code = #Patient
      * display = "Patient"
      * equivalence = #equivalent
