// Generated by make_conceptmap_fsh.py - do not edit by hand.
// Source: input/glossary_mappings.csv (confirmed rows only).
// Regenerate rather than patching: the display page beside this
// file is generated from the same rows and must agree with it.

Instance: PatientCareModelToGlossary
InstanceOf: ConceptMap
Usage: #definition
* extension[+].url = "http://hl7.org/fhir/StructureDefinition/structuredefinition-fmm"
* extension[=].valueInteger = 1
* url = "http://example.org/ConceptMap/PatientCareModelToGlossary"
* name = "PatientCareModelToGlossary"
* version = "0.9.0"
* title = "patient-care logical model elements to Common Glossary concepts"
* status = #active
* experimental = false
* date = "2026-09-07"
* copyright = "First public release - agreed by the editors and open for review. The mapping is informative: the logical models are published as released and are unchanged by it. Coverage will be extended and individual mappings may be revised as review progresses."
* description = "Maps elements of the patient-care logical models to the concepts of the Belgian Common Glossary. Published as a ConceptMap so the StructureDefinitions remain exactly as released and a change of mapping is not a change of model."

* group[+]
  * source = "https://www.ehealth.fgov.be/standards/fhir/patient-care/StructureDefinition/BeModelCarePlan"
  * target = "http://example.org/CodeSystem/BeSafeShareGlossary"
  * element[+]
    * code = #BeModelCarePlan.author
    * display = "Who is responsible for plan"
    * target[+]
      * code = #Recorder
      * display = "Recorder"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelCarePlan.basedOn
    * display = "Care plans that this care plan is based on"
    * target[+]
      * code = #OriginatingRequest
      * display = "OriginatingRequest"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelCarePlan.category
    * display = "Type of plan"
    * target[+]
      * code = #Category
      * display = "Category"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelCarePlan.identifier
    * display = "Identifiers assigned to this care plan"
    * target[+]
      * code = #BusinessIdentifier
      * display = "BusinessIdentifier"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelCarePlan.note
    * display = "Comments about the care plan"
    * target[+]
      * code = #Note
      * display = "Note"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelCarePlan.partOf
    * display = "Care plans that this care plan is part of"
    * target[+]
      * code = #PartOf
      * display = "PartOf"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelCarePlan.status
    * display = "status of the care plan"
    * target[+]
      * code = #Status
      * display = "Status"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelCarePlan.subject
    * display = "Who care plan is for"
    * target[+]
      * code = #Patient
      * display = "Patient"
      * equivalence = #equivalent

* group[+]
  * source = "https://www.ehealth.fgov.be/standards/fhir/patient-care/StructureDefinition/BeModelCareTeam"
  * target = "http://example.org/CodeSystem/BeSafeShareGlossary"
  * element[+]
    * code = #BeModelCareTeam.category
    * display = "Type of team"
    * target[+]
      * code = #Category
      * display = "Category"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelCareTeam.identifier
    * display = "Business identifiers of the care team"
    * target[+]
      * code = #BusinessIdentifier
      * display = "BusinessIdentifier"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelCareTeam.note
    * display = "Additional notes"
    * target[+]
      * code = #Note
      * display = "Note"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelCareTeam.status
    * display = "Status of the care team"
    * target[+]
      * code = #Status
      * display = "Status"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelCareTeam.subject
    * display = "the subject of care for the care team"
    * target[+]
      * code = #Patient
      * display = "Patient"
      * equivalence = #equivalent

* group[+]
  * source = "https://www.ehealth.fgov.be/standards/fhir/patient-care/StructureDefinition/BeModelGoal"
  * target = "http://example.org/CodeSystem/BeSafeShareGlossary"
  * element[+]
    * code = #BeModelGoal.category
    * display = "Category of goal"
    * target[+]
      * code = #Category
      * display = "Category"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelGoal.identifier
    * display = "Identifiers assigned to this goal"
    * target[+]
      * code = #BusinessIdentifier
      * display = "BusinessIdentifier"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelGoal.status
    * display = "Status of the goal"
    * target[+]
      * code = #Status
      * display = "Status"
      * equivalence = #equivalent

* group[+]
  * source = "https://www.ehealth.fgov.be/standards/fhir/patient-care/StructureDefinition/BeModelTask"
  * target = "http://example.org/CodeSystem/BeSafeShareGlossary"
  * element[+]
    * code = #BeModelTask.author
    * display = "Author of the task"
    * target[+]
      * code = #Recorder
      * display = "Recorder"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelTask.identifier
    * display = "Business identifiers of the task"
    * target[+]
      * code = #BusinessIdentifier
      * display = "BusinessIdentifier"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelTask.status
    * display = "Status of the task"
    * target[+]
      * code = #Status
      * display = "Status"
      * equivalence = #equivalent
