// Generated by make_conceptmap_fsh.py - do not edit by hand.
// Source: input/glossary_mappings.csv (confirmed rows only).
// Regenerate rather than patching: the display page beside this
// file is generated from the same rows and must agree with it.

Instance: PatientDossierModelToGlossary
InstanceOf: ConceptMap
Usage: #definition
* extension[+].url = "http://hl7.org/fhir/StructureDefinition/structuredefinition-fmm"
* extension[=].valueInteger = 1
* url = "http://example.org/ConceptMap/PatientDossierModelToGlossary"
* name = "PatientDossierModelToGlossary"
* title = "patient-dossier logical model elements to Common Glossary concepts"
* status = #active
* experimental = false
* date = "2026-09-07"
* copyright = "Agreed by the editors and published for public review. The mapping is informative: the logical models are published as released and are unchanged by it. Coverage will be extended and individual mappings may be revised as review progresses."
* description = "Maps elements of the patient-dossier logical models to the concepts of the Belgian Common Glossary. Published as a ConceptMap so the StructureDefinitions remain exactly as released and a change of mapping is not a change of model."

* group[+]
  * source = "https://www.ehealth.fgov.be/standards/fhir/patient-dossier/StructureDefinition/BeModelDocument"
  * target = "http://example.org/CodeSystem/BeSafeShareGlossary"
  * element[+]
    * code = #BeModelDocument.identifier
    * display = "Document identifier"
    * target[+]
      * code = #BusinessIdentifier
      * display = "BusinessIdentifier"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelDocument.status
    * display = "Status"
    * target[+]
      * code = #Status
      * display = "Status"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelDocument.subject
    * display = "Subject"
    * target[+]
      * code = #Patient
      * display = "Patient"
      * equivalence = #equivalent
