// Generated by make_conceptmap_fsh.py - do not edit by hand.
// Source: input/glossary_mappings.csv (confirmed rows only).
// Regenerate rather than patching: the display page beside this
// file is generated from the same rows and must agree with it.

Instance: UnpublishedModelToGlossary
InstanceOf: ConceptMap
Usage: #definition
* url = "http://example.org/ConceptMap/UnpublishedModelToGlossary"
* name = "UnpublishedModelToGlossary"
* title = "unpublished logical model elements to Common Glossary concepts"
* status = #active
* experimental = false
* date = "2026-09-07"
* copyright = "Published for information. This mapping carries no conformance requirement and does not modify the logical models, which are published as released. It remains subject to review: coverage will be extended and individual mappings may be revised in subsequent versions."
* description = "Maps elements of the unpublished logical models to the concepts of the Belgian Common Glossary. Published as a ConceptMap so the StructureDefinitions remain exactly as released and a change of mapping is not a change of model."

* group[+]
  * source = "https://www.ehealth.fgov.be/standards/fhir/core-clinical/StructureDefinition/BeModelDiagnosticReportDiabetes"
  * target = "http://example.org/CodeSystem/BeSafeShareGlossary"
  * element[+]
    * code = #BeModelDiagnosticReportDiabetes.BusinessIdentifier
    * display = "Report identifier for the internal supplier's business."
    * target[+]
      * code = #BusinessIdentifier
      * display = "BusinessIdentifier"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelDiagnosticReportDiabetes.Category
    * display = "Category of the report. According to ref. 8, it would be appropriate to consider setting the cardinality of the Catgory field to 1..* and to add to this report the values: 4311000179106 |Chemical pathology report (record artifact) and 408475000 |Diabetic medicine (qualifier value). 394583002 |Endocrinology (qualifier value) of the report. Look at VS_DiagRep_Category."
    * target[+]
      * code = #Category
      * display = "Category"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelDiagnosticReportDiabetes.Code
    * display = "Report code. In the diabetes project framework, it is proposed to indicate the type of procedure that leads to the production of the primary values ​​of this report. That is to say 439926003 | Ambulatory continuous glucose monitoring of interstitial tissue fluid. VS_DiagRep_Code."
    * target[+]
      * code = #Code
      * display = "Code"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelDiagnosticReportDiabetes.Device
    * display = "Identification number assigned by INAMI to the sensor type.See VS_Diab_Device"
    * target[+]
      * code = #UsedDevice
      * display = "UsedDevice"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelDiagnosticReportDiabetes.Note
    * display = "Report comments in free text format. This element will not be provided by the producer of the report, but will be provided by the healthcare provider doing the interpretation."
    * target[+]
      * code = #Note
      * display = "Note"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelDiagnosticReportDiabetes.Patient
    * display = "We refer to the patient, subject of the report, by his unique identifier.This identifier is preferably the patient's national register number (NISS). In some cases, another unique identifier may be allowed."
    * target[+]
      * code = #Patient
      * display = "Patient"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelDiagnosticReportDiabetes.Performer
    * display = "We refer to the service provider or organization that collects the observations and produces the report. [2]The unique identifier of each natural person is the NISS, while for each organization the company number serves as the unique identifier.For the Diabetes Diagnostic Report, it is: “performer = recorder.»"
    * target[+]
      * code = #Performer
      * display = "Performer"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelDiagnosticReportDiabetes.RecordedDate
    * display = "Date the report was produced."
    * target[+]
      * code = #RecordedDate
      * display = "RecordedDate"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelDiagnosticReportDiabetes.Recorder
    * display = "This refers to the service provider or organization that encodes the information.[1] The unique identifier for each natural person is the NISS, while for each organization the business number serves as the unique identifier."
    * target[+]
      * code = #Recorder
      * display = "Recorder"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelDiagnosticReportDiabetes.Status
    * display = "Report status. By default it is “Final”. Value according to the business rule on “% Data Captured” see VS_DiagRep_Status"
    * target[+]
      * code = #Status
      * display = "Status"
      * equivalence = #equivalent

* group[+]
  * source = "https://www.ehealth.fgov.be/standards/fhir/core-clinical/StructureDefinition/BeModelObservationDiabetes"
  * target = "http://example.org/CodeSystem/BeSafeShareGlossary"
  * element[+]
    * code = #BeModelObservationDiabetes.Category
    * display = "698472009 “Glucose monitoring” (FR) (invariant)See VS_Obs_Dia_Category"
    * target[+]
      * code = #Category
      * display = "Category"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelObservationDiabetes.Code
    * display = "Code corresponding to the derived value (coding to be established by SNOMED CT). Ex: AGP-PGATAR Time Above Range, TIR Time In Range…See VS_Obs_Diab_Code"
    * target[+]
      * code = #Code
      * display = "Code"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelObservationDiabetes.Patient
    * display = "Is the unique identifier of the patient. The unique identifier must be the National Patient Register Number (NISS) [1]."
    * target[+]
      * code = #Patient
      * display = "Patient"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelObservationDiabetes.RecordedDate
    * display = "Date of encoding of the observation by the Recorder. (DateTime format) See management rule 13."
    * target[+]
      * code = #RecordedDate
      * display = "RecordedDate"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelObservationDiabetes.Recorder
    * display = "Is the unique identifier (national register number)[1] of the health professional or organization (company number) which encodes the information and takes responsibility for its content."
    * target[+]
      * code = #Recorder
      * display = "Recorder"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelObservationDiabetes.Status
    * display = "445665009 “Final report” - invariant. See VS_Obs_Diab_Status Status"
    * target[+]
      * code = #Status
      * display = "Status"
      * equivalence = #equivalent

* group[+]
  * source = "https://www.ehealth.fgov.be/standards/fhir/drp/StructureDefinition/BeModelRadiologyPrescription"
  * target = "http://example.org/CodeSystem/BeSafeShareGlossary"
  * element[+]
    * code = #BeModelRadiologyPrescription.bodyLaterality
    * display = "Laterality of the anatomical location where the treatment should be applied (for example: 'Left')."
    * target[+]
      * code = #BodyLaterality
      * display = "BodyLaterality"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelRadiologyPrescription.bodySite
    * display = "Anatomical location where the treatment should be applied (for example: 'Left arm')."
    * target[+]
      * code = #BodyLocation
      * display = "BodyLocation"
      * equivalence = #equivalent

* group[+]
  * source = "https://www.ehealth.fgov.be/standards/fhir/patient-dossier/StructureDefinition/BeModelClinicalReport"
  * target = "http://example.org/CodeSystem/BeSafeShareGlossary"
  * element[+]
    * code = #BeModelClinicalReport.basedOn
    * display = "Reference to the request underlying the report"
    * target[+]
      * code = #OriginatingRequest
      * display = "OriginatingRequest"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelClinicalReport.businessIdentifier
    * display = "Business identifier of the report"
    * target[+]
      * code = #BusinessIdentifier
      * display = "BusinessIdentifier"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelClinicalReport.category
    * display = "Clinical/functional classification of the report"
    * target[+]
      * code = #Category
      * display = "Category"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelClinicalReport.code
    * display = "Code of the report"
    * target[+]
      * code = #Code
      * display = "Code"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelClinicalReport.note
    * display = "Free-text additional information"
    * target[+]
      * code = #Note
      * display = "Note"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelClinicalReport.patient
    * display = "The patient the report is about"
    * target[+]
      * code = #Patient
      * display = "Patient"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelClinicalReport.recordedDate
    * display = "Date the report was recorded / last updated"
    * target[+]
      * code = #RecordedDate
      * display = "RecordedDate"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelClinicalReport.recorder
    * display = "Who recorded the report"
    * target[+]
      * code = #Recorder
      * display = "Recorder"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelClinicalReport.status
    * display = "Status of the report"
    * target[+]
      * code = #Status
      * display = "Status"
      * equivalence = #equivalent

* group[+]
  * source = "https://www.ehealth.fgov.be/standards/fhir/perinatal/BeModeleBirthReport"
  * target = "http://example.org/CodeSystem/BeSafeShareGlossary"
  * element[+]
    * code = #BeModeleBirthReport.businessIdentifier
    * display = "Business identifier for the eBirth report"
    * target[+]
      * code = #BusinessIdentifier
      * display = "BusinessIdentifier"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModeleBirthReport.category
    * display = "The category of the eBirth report."
    * target[+]
      * code = #Category
      * display = "Category"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModeleBirthReport.code
    * display = "The code of the eBirth report."
    * target[+]
      * code = #Code
      * display = "Code"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModeleBirthReport.identifier
    * display = "Unique identifier for the eBirth report"
    * target[+]
      * code = #BusinessIdentifier
      * display = "BusinessIdentifier"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModeleBirthReport.note
    * display = "Notes or comments related to the eBirth report."
    * target[+]
      * code = #Note
      * display = "Note"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModeleBirthReport.patient
    * display = "The patient associated with the eBirth report."
    * target[+]
      * code = #Patient
      * display = "Patient"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModeleBirthReport.recordedDate
    * display = "Date and time when the eBirth report was recorded or last update."
    * target[+]
      * code = #RecordedDate
      * display = "RecordedDate"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModeleBirthReport.recorder
    * display = "The practitioner who recorded the eBirth report."
    * target[+]
      * code = #Recorder
      * display = "Recorder"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModeleBirthReport.status
    * display = "The status of the eBirth report, e.g., 'final', 'amended', 'cancelled'."
    * target[+]
      * code = #Status
      * display = "Status"
      * equivalence = #equivalent
