// Generated by make_conceptmap_fsh.py - do not edit by hand.
// Source: input/glossary_mappings.csv (confirmed rows only).
// Regenerate rather than patching: the display page beside this
// file is generated from the same rows and must agree with it.

Instance: PssModelToGlossary
InstanceOf: ConceptMap
Usage: #definition
* url = "http://example.org/ConceptMap/PssModelToGlossary"
* name = "PssModelToGlossary"
* title = "pss logical model elements to Common Glossary concepts"
* status = #active
* experimental = false
* date = "2026-09-07"
* copyright = "Published for information. This mapping carries no conformance requirement and does not modify the logical models, which are published as released. It remains subject to review: coverage will be extended and individual mappings may be revised in subsequent versions."
* description = "Maps elements of the pss logical models to the concepts of the Belgian Common Glossary. Published as a ConceptMap so the StructureDefinitions remain exactly as released and a change of mapping is not a change of model."

* group[+]
  * source = "https://www.ehealth.fgov.be/standards/fhir/pss/StructureDefinition/PSSConsentModel"
  * target = "http://example.org/CodeSystem/BeSafeShareGlossary"
  * element[+]
    * code = #PSSConsentModel.recordedDate
    * display = "Date on which the information was recorded"
    * target[+]
      * code = #RecordedDate
      * display = "RecordedDate"
      * equivalence = #equivalent

* group[+]
  * source = "https://www.ehealth.fgov.be/standards/fhir/pss/StructureDefinition/PSSRequest"
  * target = "http://example.org/CodeSystem/BeSafeShareGlossary"
  * element[+]
    * code = #PSSRequest.recordedDate
    * display = "Date on which the information was recorded"
    * target[+]
      * code = #RecordedDate
      * display = "RecordedDate"
      * equivalence = #equivalent

* group[+]
  * source = "https://www.ehealth.fgov.be/standards/fhir/pss/StructureDefinition/PSSResponse"
  * target = "http://example.org/CodeSystem/BeSafeShareGlossary"
  * element[+]
    * code = #PSSResponse.recordedDate
    * display = "Date on which the information was recorded"
    * target[+]
      * code = #RecordedDate
      * display = "RecordedDate"
      * equivalence = #equivalent
  * element[+]
    * code = #PSSResponse.status
    * display = "Status of the response"
    * target[+]
      * code = #Status
      * display = "Status"
      * equivalence = #equivalent
