// Generated by make_conceptmap_fsh.py - do not edit by hand.
// Source: input/glossary_mappings.csv (confirmed rows only).
// Regenerate rather than patching: the display page beside this
// file is generated from the same rows and must agree with it.

Instance: PssModelToGlossary
InstanceOf: ConceptMap
Usage: #definition
* url = "http://example.org/ConceptMap/PssModelToGlossary"
* name = "PssModelToGlossary"
* title = "pss logical model elements to Common Glossary concepts"
* status = #draft
* experimental = true
* date = "2026-09-07"
* copyright = "DRAFT - NOT YET REVIEWED. Proposed systematically and confirmed by an editor, but not ratified by the CareSets governance process, which is still being established. Informative, never normative: imposes no conformance requirement and does not alter the logical models, which are published unchanged. Coverage is partial and every relationship is recorded as equivalent without that equivalence having been individually verified; an unmapped element does not mean no glossary concept applies. Expect errors and please report them."
* description = "Maps elements of the pss logical models to the concepts of the Belgian Common Glossary. Published as a ConceptMap so the StructureDefinitions remain exactly as released and a change of mapping is not a change of model."

* group[+]
  * source = "https://www.ehealth.fgov.be/standards/fhir/pss/StructureDefinition/PSSConsentModel"
  * target = "http://example.org/CodeSystem/BeSafeShareGlossary"
  * element[+]
    * code = #PSSConsentModel.recordedDate
    * display = "Date on which the information was recorded"
    * target[+]
      * code = #RecordedDate
      * display = "RecordedDate"
      * equivalence = #equivalent

* group[+]
  * source = "https://www.ehealth.fgov.be/standards/fhir/pss/StructureDefinition/PSSRequest"
  * target = "http://example.org/CodeSystem/BeSafeShareGlossary"
  * element[+]
    * code = #PSSRequest.recordedDate
    * display = "Date on which the information was recorded"
    * target[+]
      * code = #RecordedDate
      * display = "RecordedDate"
      * equivalence = #equivalent

* group[+]
  * source = "https://www.ehealth.fgov.be/standards/fhir/pss/StructureDefinition/PSSResponse"
  * target = "http://example.org/CodeSystem/BeSafeShareGlossary"
  * element[+]
    * code = #PSSResponse.recordedDate
    * display = "Date on which the information was recorded"
    * target[+]
      * code = #RecordedDate
      * display = "RecordedDate"
      * equivalence = #equivalent
  * element[+]
    * code = #PSSResponse.status
    * display = "Status of the response"
    * target[+]
      * code = #Status
      * display = "Status"
      * equivalence = #equivalent
