// Generated by make_conceptmap_fsh.py - do not edit by hand.
// Source: input/glossary_mappings.csv (confirmed rows only).
// Regenerate rather than patching: the display page beside this
// file is generated from the same rows and must agree with it.

Instance: MedicationModelToGlossary
InstanceOf: ConceptMap
Usage: #definition
* url = "http://example.org/ConceptMap/MedicationModelToGlossary"
* name = "MedicationModelToGlossary"
* title = "medication logical model elements to Common Glossary concepts"
* status = #draft
* experimental = true
* date = "2026-09-07"
* copyright = "Draft release - issued for review. These mappings have not yet been ratified by the CareSets governance process, which is being established alongside this release. They are informative, not normative: they impose no conformance requirement and do not alter the logical models, which are published exactly as released. Coverage is partial and the relationships are indicative, so implementations should not yet rely on them."
* description = "Maps elements of the medication logical models to the concepts of the Belgian Common Glossary. Published as a ConceptMap so the StructureDefinitions remain exactly as released and a change of mapping is not a change of model."

* group[+]
  * source = "https://www.ehealth.fgov.be/standards/fhir/medication/StructureDefinition/BeModelDosagingInformation"
  * target = "http://example.org/CodeSystem/BeSafeShareGlossary"
  * element[+]
    * code = #BeModelDosagingInformation.routeOfAdministration
    * display = "Route of administration"
    * target[+]
      * code = #RouteOfAdministration
      * display = "RouteOfAdministration"
      * equivalence = #equivalent

* group[+]
  * source = "https://www.ehealth.fgov.be/standards/fhir/medication/StructureDefinition/BeModelMedication"
  * target = "http://example.org/CodeSystem/BeSafeShareGlossary"
  * element[+]
    * code = #BeModelMedication.batch.lotNumber
    * display = "Batch number"
    * target[+]
      * code = #LotNumber
      * display = "LotNumber"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelMedication.code
    * display = "Code for the medication that is actually being specified. This can be a product code, a virtual product code, or a package code."
    * target[+]
      * code = #Code
      * display = "Code"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelMedication.status
    * display = "Status of the medication (active, inactive, etc.)"
    * target[+]
      * code = #Status
      * display = "Status"
      * equivalence = #equivalent

* group[+]
  * source = "https://www.ehealth.fgov.be/standards/fhir/medication/StructureDefinition/BeModelMedicationDispense"
  * target = "http://example.org/CodeSystem/BeSafeShareGlossary"
  * element[+]
    * code = #BeModelMedicationDispense.identifier
    * display = "The business identifier(s) for the medication dispense record"
    * target[+]
      * code = #BusinessIdentifier
      * display = "BusinessIdentifier"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelMedicationDispense.note
    * display = "Additional information about the dispense - this can be relevant history, any remarks by the patient or professional, etc."
    * target[+]
      * code = #Note
      * display = "Note"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelMedicationDispense.patient
    * display = "The person for which the medication is dispensed"
    * target[+]
      * code = #Patient
      * display = "Patient"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelMedicationDispense.recordedDate
    * display = "The date (or date+time) when the dispense was recorded"
    * target[+]
      * code = #RecordedDate
      * display = "RecordedDate"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelMedicationDispense.status
    * display = "The status of the dispense record"
    * target[+]
      * code = #Status
      * display = "Status"
      * equivalence = #equivalent

* group[+]
  * source = "https://www.ehealth.fgov.be/standards/fhir/medication/StructureDefinition/BeModelMedicationLine"
  * target = "http://example.org/CodeSystem/BeSafeShareGlossary"
  * element[+]
    * code = #BeModelMedicationLine.adherence.status
    * display = "The status - taking, not taking,..."
    * target[+]
      * code = #Status
      * display = "Status"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelMedicationLine.identifier
    * display = "Unique identifier"
    * target[+]
      * code = #BusinessIdentifier
      * display = "BusinessIdentifier"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelMedicationLine.note
    * display = "A note captured by a professional"
    * target[+]
      * code = #Note
      * display = "Note"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelMedicationLine.patient
    * display = "Patient"
    * target[+]
      * code = #Patient
      * display = "Patient"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelMedicationLine.recordedDate
    * display = "Timestamp the medication line content was recorded or last updated."
    * target[+]
      * code = #RecordedDate
      * display = "RecordedDate"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelMedicationLine.recorder
    * display = "Recorder"
    * target[+]
      * code = #Recorder
      * display = "Recorder"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelMedicationLine.status
    * display = "Status of the line entry"
    * target[+]
      * code = #Status
      * display = "Status"
      * equivalence = #equivalent

* group[+]
  * source = "https://www.ehealth.fgov.be/standards/fhir/medication/StructureDefinition/BeModelMedicationPrescription"
  * target = "http://example.org/CodeSystem/BeSafeShareGlossary"
  * element[+]
    * code = #BeModelMedicationPrescription.identifier
    * display = "Business identifier(s) for the prescription"
    * target[+]
      * code = #BusinessIdentifier
      * display = "BusinessIdentifier"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelMedicationPrescription.note
    * display = "Additional information or comments"
    * target[+]
      * code = #Note
      * display = "Note"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelMedicationPrescription.patient
    * display = "The person for whom the medication is prescribed/ordered"
    * target[+]
      * code = #Patient
      * display = "Patient"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelMedicationPrescription.recordedDate
    * display = "Time of authoring the prescription/draft in the information system"
    * target[+]
      * code = #RecordedDate
      * display = "RecordedDate"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelMedicationPrescription.status
    * display = "Status of the prescription, this should not be status of treatment"
    * target[+]
      * code = #Status
      * display = "Status"
      * equivalence = #equivalent
