// Generated by make_conceptmap_fsh.py - do not edit by hand.
// Source: input/glossary_mappings.csv (confirmed rows only).
// Regenerate rather than patching: the display page beside this
// file is generated from the same rows and must agree with it.

Instance: CoreClinicalModelToGlossary
InstanceOf: ConceptMap
Usage: #definition
* url = "http://example.org/ConceptMap/CoreClinicalModelToGlossary"
* name = "CoreClinicalModelToGlossary"
* title = "core-clinical logical model elements to Common Glossary concepts"
* status = #active
* experimental = false
* date = "2026-09-07"
* copyright = "Published for review. This mapping is provided for information. It carries no conformance requirement and does not modify the logical models, which are published as released. It has not yet completed the CareSets governance review; its coverage is not exhaustive and individual mappings may be revised. Implementations should not depend on it in its present version."
* description = "Maps elements of the core-clinical logical models to the concepts of the Belgian Common Glossary. Published as a ConceptMap so the StructureDefinitions remain exactly as released and a change of mapping is not a change of model."

* group[+]
  * source = "https://www.ehealth.fgov.be/standards/fhir/core-clinical/StructureDefinition/BeModelBodySite"
  * target = "http://example.org/CodeSystem/BeSafeShareGlossary"
  * element[+]
    * code = #BeModelBodySite.bodyLaterality
    * display = "The laterality of a body site - the side of the body"
    * target[+]
      * code = #BodyLaterality
      * display = "BodyLaterality"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelBodySite.bodyLocation
    * display = "Code that identifies the anatomical location of the specimen on the subject's body"
    * target[+]
      * code = #BodyLocation
      * display = "BodyLocation"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelBodySite.bodyTopography
    * display = "The topography of the location of the specimen on the subject's body"
    * target[+]
      * code = #BodyTopography
      * display = "BodyTopography"
      * equivalence = #equivalent

* group[+]
  * source = "https://www.ehealth.fgov.be/standards/fhir/core-clinical/StructureDefinition/BeModelClinicalObservation"
  * target = "http://example.org/CodeSystem/BeSafeShareGlossary"
  * element[+]
    * code = #BeModelClinicalObservation.bodySite
    * display = "The site on the subject's body where the observation was made (i.e. the target site)"
    * target[+]
      * code = #BodyLocation
      * display = "BodyLocation"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelClinicalObservation.category
    * display = "A code that classifies the general type of observation being made"
    * target[+]
      * code = #Category
      * display = "Category"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelClinicalObservation.code
    * display = "Describes what was observed. Sometimes this is called the observation 'name'"
    * target[+]
      * code = #Code
      * display = "Code"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelClinicalObservation.device
    * display = "The device used to generate the observation data"
    * target[+]
      * code = #UsedDevice
      * display = "UsedDevice"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelClinicalObservation.identifier
    * display = "Unique identifier for the observation"
    * target[+]
      * code = #BusinessIdentifier
      * display = "BusinessIdentifier"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelClinicalObservation.note
    * display = "Comments about the observation or the results"
    * target[+]
      * code = #Note
      * display = "Note"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelClinicalObservation.patient
    * display = "The patient that this observation is about"
    * target[+]
      * code = #Patient
      * display = "Patient"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelClinicalObservation.performer
    * display = "The professional that performed the observation"
    * target[+]
      * code = #Performer
      * display = "Performer"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelClinicalObservation.recordedDate
    * display = "Date when the observation was recorded"
    * target[+]
      * code = #RecordedDate
      * display = "RecordedDate"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelClinicalObservation.recorder
    * display = "Person, organisation or device that recorded the observation"
    * target[+]
      * code = #Recorder
      * display = "Recorder"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelClinicalObservation.status
    * display = "The status of the result value."
    * target[+]
      * code = #Status
      * display = "Status"
      * equivalence = #equivalent

* group[+]
  * source = "https://www.ehealth.fgov.be/standards/fhir/core-clinical/StructureDefinition/BeModelProblem"
  * target = "http://example.org/CodeSystem/BeSafeShareGlossary"
  * element[+]
    * code = #BeModelProblem.asserter
    * display = "Asserter"
    * target[+]
      * code = #Asserter
      * display = "Asserter"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelProblem.bodySite
    * display = "Body Site"
    * target[+]
      * code = #BodyLocation
      * display = "BodyLocation"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelProblem.bodySite.laterality
    * display = "Body Laterality"
    * target[+]
      * code = #BodyLaterality
      * display = "BodyLaterality"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelProblem.bodySite.localisation
    * display = "Body Localisation"
    * target[+]
      * code = #BodyLocation
      * display = "BodyLocation"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelProblem.category
    * display = "Category"
    * target[+]
      * code = #Category
      * display = "Category"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelProblem.clinicalStatus
    * display = "Clinical Status"
    * target[+]
      * code = #ClinicalStatus
      * display = "ClinicalStatus"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelProblem.code
    * display = "Code"
    * target[+]
      * code = #Code
      * display = "Code"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelProblem.identifier
    * display = "Business Identifier"
    * target[+]
      * code = #BusinessIdentifier
      * display = "BusinessIdentifier"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelProblem.note
    * display = "Note"
    * target[+]
      * code = #Note
      * display = "Note"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelProblem.recordedDate
    * display = "Recorded Date"
    * target[+]
      * code = #RecordedDate
      * display = "RecordedDate"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelProblem.recorder
    * display = "Recorder"
    * target[+]
      * code = #Recorder
      * display = "Recorder"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelProblem.subject
    * display = "Patient"
    * target[+]
      * code = #Patient
      * display = "Patient"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelProblem.verificationStatus
    * display = "Verification Status"
    * target[+]
      * code = #VerificationStatus
      * display = "VerificationStatus"
      * equivalence = #equivalent

* group[+]
  * source = "https://www.ehealth.fgov.be/standards/fhir/core-clinical/StructureDefinition/BeModelProcedure"
  * target = "http://example.org/CodeSystem/BeSafeShareGlossary"
  * element[+]
    * code = #BeModelProcedure.bodySite
    * display = "The site on the patient's body where the procedure was performed"
    * target[+]
      * code = #BodyLocation
      * display = "BodyLocation"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelProcedure.category
    * display = "Type or nature of the procedure. For example: surgical, psychiatric or chiropractic procedures"
    * target[+]
      * code = #Category
      * display = "Category"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelProcedure.code
    * display = "Identification of the procedure (SNOMED-CT Procedure concept)"
    * target[+]
      * code = #Code
      * display = "Code"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelProcedure.identifier
    * display = "Unique identifier for the procedure"
    * target[+]
      * code = #BusinessIdentifier
      * display = "BusinessIdentifier"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelProcedure.note
    * display = "Additional information about the procedure"
    * target[+]
      * code = #Note
      * display = "Note"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelProcedure.partOf
    * display = "Part of the event being referenced: procedure, observation (symptoms) or problem (disease). For example: Blood draw (procedure) is part of the diagnostic observation (Observation)"
    * target[+]
      * code = #PartOf
      * display = "PartOf"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelProcedure.patient
    * display = "The patient that is the subject of the procedure."
    * target[+]
      * code = #Patient
      * display = "Patient"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelProcedure.performer
    * display = "Person who performed the procedure."
    * target[+]
      * code = #Performer
      * display = "Performer"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelProcedure.recordedDate
    * display = "Date of the last modification/recording of the procedure"
    * target[+]
      * code = #RecordedDate
      * display = "RecordedDate"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelProcedure.recorder
    * display = "Person, organization or device that recorded the procedure."
    * target[+]
      * code = #Recorder
      * display = "Recorder"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelProcedure.status
    * display = "Procedure status (not-done, stopped, completed, entered-in-error). Note: 'not-done' is out of scope as it implies planning. Business Rule: 'completed' by default"
    * target[+]
      * code = #Status
      * display = "Status"
      * equivalence = #equivalent
  * element[+]
    * code = #BeModelProcedure.usedDevice
    * display = "Devices or materials used temporarily during the procedure. For example: surgical robot, intraoperative imaging, neuronavigation. This also includes substances such as gels. Standard small instruments such as scalpels and syringes are not recorded"
    * target[+]
      * code = #UsedDevice
      * display = "UsedDevice"
      * equivalence = #equivalent
